import json
import os
import sys
import urllib.request
import urllib.parse
import ssl

# =================================================================================================
# [Ka0S] Process Failed Pods -> iTop Tickets
# =================================================================================================
# Propósito: Leer el JSON de pods fallidos y crear un ticket en iTop por cada uno.
# Autor: Ka0s Architect
# =================================================================================================

def create_itop_ticket(pod, itop_url, itop_user, itop_pass):
    metadata = pod.get('metadata', {})
    status = pod.get('status', {})
    
    namespace = metadata.get('namespace', 'unknown')
    name = metadata.get('name', 'unknown')
    phase = status.get('phase', 'Unknown')
    
    # Construir descripción detallada
    description = f"<h1>Automated Pod Failure Detected</h1>"
    description += f"<ul>"
    description += f"<li><b>Pod:</b> {name}</li>"
    description += f"<li><b>Namespace:</b> {namespace}</li>"
    description += f"<li><b>Phase:</b> {phase}</li>"
    description += f"</ul>"
    
    description += "<h3>Conditions</h3><ul>"
    for cond in status.get('conditions', []):
        if cond.get('status') != 'True':
            description += f"<li><b>{cond.get('type')}:</b> {cond.get('message', 'No message')} (Reason: {cond.get('reason', 'Unknown')})</li>"
    description += "</ul>"

    # Preparar payload OQL
    # Usamos OQL para buscar dinámicamente el Caller y la Org basados en el usuario de API
    user_oql = f"SELECT Person JOIN User ON User.contactid = Person.id WHERE User.login = '{itop_user}'"
    org_oql = f"SELECT Organization JOIN Person ON Person.org_id = Organization.id JOIN User ON User.contactid = Person.id WHERE User.login = '{itop_user}'"

    json_data = {
        "operation": "core/create",
        "class": "UserRequest",
        "comment": "Auto-generated by Ka0s Audit",
        "fields": {
            "org_id": org_oql,
            "caller_id": user_oql,
            "title": f"[K8s Audit] Pod Failed: {namespace}/{name}",
            "description": description,
            "origin": "monitoring",
            "service_id": "SELECT Service WHERE name LIKE '%Kubernetes%' OR name LIKE '%Infra%'", # Intento de asignar servicio, fallback a default si no existe podría fallar, mejor omitir si no estamos seguros o usar un genérico.
            # Omitimos service_id para evitar errores si no existe el servicio específico.
            "impact": 2, # Medium
            "urgency": 2  # Medium
        }
    }

    # Codificar payload
    data = urllib.parse.urlencode({'json_data': json.dumps(json_data)}).encode('utf-8')
    
    # URL completa
    api_url = f"{itop_url}/webservices/rest.php?version=1.3"
    
    # Headers
    headers = {
        # 'Content-Type': 'application/x-www-form-urlencoded' # urllib lo maneja por defecto al usar urlencode
    }
    
    # Autenticación Básica
    # iTop usa user/pass en el POST body o Basic Auth? 
    # El ejemplo de curl usa -u user:pass que es Basic Auth.
    auth_str = f"{itop_user}:{itop_pass}"
    import base64
    b64_auth = base64.b64encode(auth_str.encode()).decode()
    headers['Authorization'] = f"Basic {b64_auth}"

    # Contexto SSL (ignorar verificación si es autofirmado, como en curl -k)
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    try:
        req = urllib.request.Request(api_url, data=data, headers=headers, method='POST')
        with urllib.request.urlopen(req, context=ctx) as response:
            resp_body = response.read().decode('utf-8')
            resp_json = json.loads(resp_body)
            
            if resp_json.get('code') == 0:
                print(f"[SUCCESS] Ticket created for {name}: {resp_json.get('objects', {}).get(next(iter(resp_json.get('objects', {}))), {}).get('key')}")
            else:
                print(f"[ERROR] Failed to create ticket for {name}: {resp_json.get('message')}")
                print(f"Debug: {resp_body}")
                
    except Exception as e:
        print(f"[EXCEPTION] Error communicating with iTop: {str(e)}")

def main():
    # 1. Obtener Configuración
    itop_url = os.environ.get('ITOP_URL')
    itop_user = os.environ.get('ITOP_USER')
    itop_pass = os.environ.get('ITOP_PASSWORD')
    file_path = os.environ.get('FAILED_PODS_FILE', 'audit/kube/failed_pods.json')

    if not all([itop_url, itop_user, itop_pass]):
        print("[ERROR] Missing ITOP_URL, ITOP_USER or ITOP_PASSWORD environment variables.")
        sys.exit(1)

    # 2. Leer JSON
    if not os.path.exists(file_path):
        print(f"[INFO] No results file found at {file_path}. Nothing to do.")
        sys.exit(0)

    try:
        with open(file_path, 'r') as f:
            pods = json.load(f)
    except json.JSONDecodeError:
        print("[ERROR] Invalid JSON format in results file.")
        sys.exit(1)

    if not pods:
        print("[INFO] No failed pods found in list.")
        sys.exit(0)

    print(f"[INFO] Processing {len(pods)} failed pods...")

    # 3. Procesar cada Pod
    for pod in pods:
        create_itop_ticket(pod, itop_url, itop_user, itop_pass)

if __name__ == "__main__":
    main()
