version: '3.3'
services:
  portal:
    image: ka0score/portal-runner:0.0.1
    command:
     - sh
     - -c
     - |
      # Configurar NVM para el usuario actual
      export NVM_DIR="/root/.nvm"
      [ -s "/nvm.sh" ] && \. "/nvm.sh"
      [ -s "/bash_completion" ] && \. "/bash_completion"
      echo "PORTAL --- Iniciando como usuario `whoami` el proceso del Portal---"
      echo "Estamos aqui... "
      pwd
      ls -la
      echo "PORTAL --- Instalamos yarn... ---"
      npm install -g corepack
      echo "PORTAL --- Go to Ka0s Core App... ---"
      sh startup.sh
      yarn cache clean --all
      echo "PORTAL --- Cache limpia... ---"
      echo "PORTAL --- Borramos los modulos... ---"
      sudo rm -rf node_modules
      yarn install
      echo "PORTAL --- Instaladas dependencias... ---"
      yarn start
    working_dir: /app
    environment:
      NODE_ENV: production
    ports:
     - 3000:3000
     - 7007:7007
    volumes:
     - portal_data:/app
    networks:
     - portal
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
networks:
  portal:
    driver: overlay
volumes:
  portal_data:
    external: true
