apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama-gen

resources:
  - namespace.yaml
  - ollama-gen-pvc.yaml
  - ollama-gen-service.yaml
  - ollama-gen-deployment.yaml

