apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-gen-pvc
  namespace: ollama-gen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client

