apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-app-pvc
  namespace: n8n
  labels:
    app: n8n
    core.kaos.io/type: automation
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: n8n-app-pv
