version: "3.8"

volumes:
  portal_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.52,rw,nolock,soft
      device: :/portal

secrets:
  POSTGRES_PASSWORD:
    external: true
  BACKEND_SECRET:
    external: true
  FRONTEND_SECRET:
    external: true
  SSL_CERT:
    external: true
  SSL_KEY:
    external: true

configs:
  appconfig_yaml:
    external: true
  appconfig_production_yaml:
    external: true
  cataloginfo_yaml:
    external: true
  backstage_json:
    external: true

services:
  backend:
    image: ka0score/portal-backend:0.0.0
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      BACKEND_SECRET_FILE: /run/secrets/BACKEND_SECRET
    networks:
      - portal_net
    secrets:
      - POSTGRES_PASSWORD
      - BACKEND_SECRET
    working_dir: /app
    command: yarn start --cwd packages/backend
    configs:
      - source: appconfig_yaml
        target: /app/app-config.yaml
      - source: appconfig_production_yaml
        target: /app/app-config.production.yaml
      - source: cataloginfo_yaml
        target: /app/catalog-info.yaml
      - source: backstage_json
        target: /app/backstage.json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: ka0score/portal-frontend:0.0.0
    environment:
      NODE_ENV: production
      FRONTEND_SECRET_FILE: /run/secrets/FRONTEND_SECRET
    secrets:
      - FRONTEND_SECRET
      - SSL_CERT
      - SSL_KEY
    ports:
      - "3000:3000"
    networks:
      - portal_net
    configs:
      - source: appconfig_yaml
        target: /app/app-config.yaml
      - source: appconfig_production_yaml
        target: /app/app-config.production.yaml
      - source: cataloginfo_yaml
        target: /app/catalog-info.yaml
      - source: backstage_json
        target: /app/backstage.json
    command: yarn start --cwd packages/app
    working_dir: /app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  portal_net:
    driver: overlay