version: "3.8"

volumes:
  portal_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.52,rw,nolock,soft
      device: :/portal

secrets:
  POSTGRES_PASSWORD:
    external: true
  BACKEND_SECRET:
    external: true
  FRONTEND_SECRET:
    external: true
  SSL_CERT:
    external: true
  SSL_KEY:
    external: true

configs:
  preinstall_deps_sh:
    external: true
  app_config_yaml:
    file: /Users/santale/ka0s-klaus/ka0s/core/portal/portal/app-config.yaml
  app_config_production_yaml:
    file: /Users/santale/ka0s-klaus/ka0s/core/portal/portal/app-config.production.yaml
  catalog_info_yaml:
    file: /Users/santale/ka0s-klaus/ka0s/core/portal/portal/catalog-info.yaml
  backstage_json:
    file: /Users/santale/ka0s-klaus/ka0s/core/portal/portal/backstage.json

services:
  backend:
    image: ka0score/portal-backend:0.0.0
    build:
      context: ../../portal
      dockerfile: packages/backend/Dockerfile
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      BACKEND_SECRET_FILE: /run/secrets/BACKEND_SECRET
    secrets:
      - POSTGRES_PASSWORD
      - BACKEND_SECRET
    # volumes:
    #   - portal_data:/app
    working_dir: /app/packages/backend
    command: sh -c "yarn install && yarn start"

  frontend:
    image: ka0score/portal-frontend:0.0.0
    build:
      context: ../../portal
      dockerfile: packages/app/Dockerfile
    environment:
      NODE_ENV: production
      FRONTEND_SECRET_FILE: /run/secrets/FRONTEND_SECRET
    secrets:
      - FRONTEND_SECRET
      - SSL_CERT
      - SSL_KEY
    ports:
      - "3000:3000"
    # volumes:
    #   - portal_data:/app
    networks:
      - portal_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: preinstall_deps_sh
        target: /app/preinstall-deps.sh
      - source: app_config_yaml
        target: /app/app-config.yaml
      - source: app_config_production_yaml
        target: /app/app-config.production.yaml
      - source: catalog_info_yaml
        target: /app/catalog-info.yaml
      - source: backstage_json
        target: /app/backstage.json
    command: sh -c "yarn install && yarn start"

networks:
  portal_net:
    driver: overlay