apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama

resources:
  - namespace.yaml
  - ollama-pvc.yaml
  - ollama-service.yaml
  - ollama-deployment.yaml
  - ollama-embed-fleet-deployment.yaml
  - ollama-embed-service.yaml
  - ollama-ingress.yaml
  - pull-model-job.yaml
