site_name: 'Ka0s Local Documentation'
site_description: 'Documentación local del proyecto Ka0s'
site_url: 'http://core.ka0s.io:3000'

# Configuración correcta
docs_dir: 'docs'     # Directorio docs como subdirectorio
site_dir: 'site'     # Directorio site en la raíz, fuera de docs

nav:
  - Home: index.md
  - Documentation: README.md
  - Core: ka0s/ka0s.md
  - Ka0s Core: ka0s_core/ka0s_core.md
  - Dashboard: ka0s_dashboard/ka0s_dashboard_user.md
  - Docker: ka0s_docker/docker.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true