apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: test
