apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-replicas
  namespace: runners
data:
  replicas: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-sa
  namespace: runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-editor
  namespace: runners
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-can-edit-configmap
  namespace: runners
subjects:
- kind: ServiceAccount
  name: manager-sa
  namespace: runners
roleRef:
  kind: Role
  name: configmap-editor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-manager
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-manager
  template:
    metadata:
      labels:
        app: github-actions-manager
    spec:
      serviceAccountName: manager-sa
      volumes:
        - name: manager-script
          configMap:
            name: manager-script
            defaultMode: 0755
        - name: github-private-key
          secret:
            secretName: github-secrets
        - name: shared-data
          emptyDir: {}
      containers:
        - name: manager
          image: ka0score/actions-runner:1.0.3 # Reemplaza con tu imagen
          command: ["/bin/sh", "-c", "/scripts/manager.sh"]
          env:
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: GITHUB_APP_ID
            - name: GITHUB_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: GITHUB_INSTALLATION_ID
            - name: GITHUB_SCOPE_ORG
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: GITHUB_SCOPE_ORG
          volumeMounts:
            - name: manager-script
              mountPath: /scripts
            - name: github-private-key
              mountPath: /etc/github
            - name: shared-data
              mountPath: /shared
        - name: configmap-updater
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                if [ -f /shared/replicas.txt ]; then
                  REPLICAS=$(cat /shared/replicas.txt)
                  if [ -n "$REPLICAS" ]; then
                    echo "Actualizando ConfigMap a $REPLICAS réplicas..."
                    kubectl patch configmap runner-replicas -n runners --type merge -p "{\"data\":{\"replicas\":\"$REPLICAS\"}}"
                    rm /shared/replicas.txt
                  fi
                fi
                sleep 10
              done
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner
  namespace: runners
spec:
  replicas: 1 # Este valor será gestionado por un controlador externo
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
        - name: runner
          image: ka0score/actions-runner:1.0.3
          env:
          - name: REPO_URL
            value: "https://github.com/Ka0s-Klaus"
          - name: RUNNER_LABELS
            value: "self-hosted,linux,x64,swarm-runners"
          - name: EPHEMERAL
            value: "true"
          - name: GITHUB_TOKEN
            value: ""
          - name: GITHUB_SCOPE_ORG
            valueFrom:
              secretKeyRef:
                name: github-secrets
                key: github_scope_org
          command: ["sh", "-c", "./config.sh --unattended --replace --url https://github.com/$GITHUB_SCOPE_ORG --token $GITHUB_TOKEN --labels swarm-runners --runnergroup swarm-runners && ./run.sh"]
      restartPolicy: Always