apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llama-server

resources:
  - namespace.yaml
  - pvc.yaml
  - model-download-configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
