apiVersion: v1
kind: Service
metadata:
  name: llama-server
  namespace: llama-server
  labels:
    app: llama-server
    managed-by: ka0s-core-cd
spec:
  selector:
    app: llama-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
