global:
  scrape_interval:     30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['::9090']

  - job_name: 'nodexporter-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['::9100']

  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets: ['::8080']