version: '3.8'

services:
  github-actions-manager:
    # --- SIN CAMBIOS ---
    image: ka0score/actions-runner:1.0.3
    user: root
    environment:
      - RUNNER_SERVICE_NAME=kaosrunner_github-actions-runner
      - MAX_RUNNERS=10
      - LOOP_INTERVAL=30
    command:
      - "sh"
      - "-c"
      - |
        echo "--- Iniciando como usuario `whoami` el proceso del manager---"
        date
        sh /manager.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: manager_script
        target: /manager.sh
    secrets:
      - github_app_id
      - github_installation_id
      - github_app_private_key
      - github_scope
      - github_scope_org
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  github-actions-runner:
    image: ka0score/actions-runner:1.0.2
    # --- ¡VARIABLES DE ENTORNO! ---
    environment:
      - REPO_URL=https://github.com/Ka0s-Klaus
      - RUNNER_LABELS=self-hosted,linux,x64,swarm-runner
      - EPHEMERAL=true
    configs:
      - source: runner_packages
        target: /home/runner/runner_packages.list
    command:
      - "sh"
      - "-c"
      - |
        echo "--- Iniciando como usuario `whoami` $$GITHUB_TOKEN ---"
        RUNNER_NAME="swarm-runner-`hostname`"
        echo "--- Ejecutado el runner $$RUNNER_NAME ---"
        
        ./config.sh --unattended --replace \
          --url https://github.com/Ka0s-Klaus \
          --token $$GITHUB_TOKEN \
          --labels swarm-runner \
          --runnergroup swarm-runners \
          --ephemeral
          
        sleep 5  
        echo "--- Configuración completada. Ejecutando el runner. ---"
        sleep 5
        ./run.sh
    deploy:
      mode: replicated
      replicas: 0

# ... (secrets y manager_script sin cambios) ...
secrets:
  github_app_id:
    external: true
  github_installation_id:
    external: true
  github_app_private_key:
    external: true
  github_scope:
    external: true
  github_scope_org:
    external: true

configs:
  manager_script:
    external: true
  # --- ¡NUEVO! Declaramos el config de paquetes ---
  runner_packages:
    external: true