version: '3.3'
services:
  github-actions-manager:
    image: ka0score/actions-runner:1.0.3
    command:
     - sh
     - -c
     - |
      echo "--- Iniciando como usuario `whoami` el proceso del manager---"
      date
      sh /manager.sh
    user: root
    environment:
      LOOP_INTERVAL: '30'
      MAX_RUNNERS: '0'
      RUNNER_SERVICE_NAME: kaosrunner_github-actions-runner
      TZ: Europe/Madrid
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    secrets:
     - github_app_id
     - github_app_private_key
     - github_installation_id
     - github_scope
    configs:
     -
      source: manager_script
      target: /manager.sh
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
  github-actions-runner:
    image: ka0score/actions-runner:1.0.2
    command:
     - sh
     - -c
     - "echo \"--- Iniciando como usuario `whoami` $$GITHUB_TOKEN ---\"\nRUNNER_NAME=\"\
      swarm-runner-`hostname`\"\necho \"--- Ejecutado el runner $$RUNNER_NAME ---\"\
      \n\n./config.sh --unattended --replace \\\n  --url https://github.com/Ka0s-Klaus\
      \ \\\n  --token $$GITHUB_TOKEN \\\n  --labels swarm-runner \\\n  --runnergroup\
      \ swarm-runners \\\n  --ephemeral\n  --disableupdate\n  \nsleep 5  \necho \"\
      --- Configuración completada. Ejecutando el runner. ---\"\nsleep 5\n./run.sh\n"
    environment:
      EPHEMERAL: 'true'
      GITHUB_TOKEN: BXSBTPKNYUEUKXHOOFIMGHTI2GLITAVPNFXHG5DBNRWGC5DJN5XF62LEZYCSPHAAWFUW443UMFWGYYLUNFXW4X3UPFYGLN2JNZ2GKZ3SMF2GS33OJFXHG5DBNRWGC5DJN5XA
      REPO_URL: https://github.com/Ka0s-Klaus
      RUNNER_LABELS: self-hosted,linux,x64,swarm-runner
      TZ: Europe/Madrid
    networks:
     - default
    configs:
     -
      source: runner_packages
      target: /home/runner/runner_packages.list
    logging:
      driver: json-file
    deploy:
      replicas: 7
networks:
  default:
    driver: overlay
configs:
  manager_script:
    external: true
  runner_packages:
    external: true
secrets:
  github_app_id:
    external: true
  github_app_private_key:
    external: true
  github_installation_id:
    external: true
  github_scope:
    external: true
