version: '3.8'

services:
  github-actions-manager:
    # ... sin cambios ...
    image: alpine:latest
    environment:
      - RUNNER_SERVICE_NAME=kaosrunner_github-actions-runner
      - MAX_RUNNERS=30
      - LOOP_INTERVAL=15
    command: >
      sh -c "
        apk add --no-cache curl jq docker-cli openssl coreutils &&
        sh /manager.sh
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: manager_script
        target: /manager.sh
    secrets:
      - github_app_id
      - github_installation_id
      - github_app_private_key
      - github_scope
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  github-actions-runner:
    image: ghcr.io/actions/actions-runner:latest
    environment:
      - REPO_URL=https://github.com/Ka0s-Klaus/ka0s
      - RUNNER_LABELS=self-hosted,linux,x64,swarm-runner
      - EPHEMERAL=true
    
    command:
      - "sh"
      - "-c"
      - |
        RUNNER_NAME="swarm-runner-$(hostname )"
        echo "--- Configurando el runner ${RUNNER_NAME} ---"

        # --- ¡TU CORRECCIÓN APLICADA! Sin comillas innecesarias ---
        ./config.sh --unattended --replace \
          --url https://github.com/Ka0s-Klaus/ka0s \
          --token BO7XQANZ6B5WM5T66FW5WV3IZUKT4 \
          --labels swarm-runner \
          --runnergroup swarm-runner \
          --ephemeral
          
        echo "--- Configuración completada. Ejecutando el runner. ---"
        
        ./run.sh
    deploy:
      mode: replicated
      replicas: 0

# ... (secrets y configs sin cambios)
secrets:
  github_app_id:
    external: true
  github_installation_id:
    external: true
  github_app_private_key:
    external: true
  github_scope:
    external: true

configs:
  manager_script:
    external: true

