apiVersion: v1
kind: Secret
metadata:
  name: knowledge-sources
  namespace: ka0s-knowledge
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:vqhdW8eMRHjW3I3RXZjNUA9B5EUpjARXfaXjGxGnAns=@mongo.mongo.svc.cluster.local:27017/?authSource=admin&directConnection=true"
  POSTGRES_IA_HOST: "postgresql-ia.postgresql-ia.svc.cluster.local"
  POSTGRES_IA_PORT: "5432"
  POSTGRES_IA_DB: "ka0s_memory"
  POSTGRES_IA_USER: "ka0s_ai"
  POSTGRES_IA_PASSWORD: "change_me_in_production_vector_db_123!"
