apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ka0s-knowledge

resources:
  - namespace.yaml
  - knowledge-sources-secret.yaml
  - mongo-vectorize-json-cronjob.yaml
  - mongo-vectorize-log-cronjob.yaml
  - mongo-vectorize-server-cronjob.yaml
  - mongo-vectorize-k8config-cronjob.yaml

configMapGenerator:
  - name: mongo-vectorize-scripts
    files:
      - mongo_ingest.py=scripts/mongo_ingest.py
      - mongo_k8config_diff.py=scripts/mongo_k8config_diff.py
      - requirements.txt=scripts/requirements.txt

generatorOptions:
  disableNameSuffixHash: true
