apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-pvc
  namespace: zabbix
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: zabbix-server-pv