apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-pvc
  namespace: anythingllm
  labels:
    app: anythingllm
    managed-by: ka0s-core-cd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
