apiVersion: v1
kind: PersistentVolume
metadata:
  name: planka-data-pv
  labels:
    type: local
    app: planka-data
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/planka/data"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8-node-20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-data-pvc
  namespace: planka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: planka-data
