apiVersion: v1
kind: ResourceQuota
metadata:
  name: planka-compute-resources
  namespace: planka
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
