name: Deploy to Server
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: |
        docker build -t linux-automator .
        docker save linux-automator > image.tar
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker load < image.tar
          docker-compose up -d