FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    python3 \
    nodejs \
    npm \
    cron \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN npm install
CMD ["bash", "start.sh"]  # Inicia Cron + Servidor Node