version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: User Admin
      MONGO_INITDB_ROOT_PASSWORD: Admin Password
    volumes:
      - kaos-mongo:/data/db

volumes:
  kaos-mongo:
    external: true