apiVersion: actions.summerwind.dev/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: swarm-runners-scaleset
  namespace: actions-runner-system
spec:
  # La URL de tu repositorio u organización en GitHub.
  # Los runners se registrarán en este nivel.
  githubConfigUrl: "https://github.com/Ka0s-Klaus/Ka0s"

  # El nombre del grupo de runners.
  # Los runners se añadirán a este grupo.
  # DEBES configurar las etiquetas para este grupo en la UI de GitHub.
  # Etiquetas a configurar en GitHub: self-hosted, linux, x64, swarm-runners
  runnerGroup: "swarm-runners"

  # Configuración de autoescalado
  maxRunners: 5
  minRunners: 1

  # Esta es la plantilla para los pods de los runners que se crearán.
  template:
    metadata:
      # Etiquetas del Pod, usadas por Kubernetes para selección.
      # Es importante para el paso de verificación en deploy.sh.
      labels:
        runner-template: swarm-runner
    spec:
      containers:
      - name: runner
        # Usar una imagen con dind (Docker-in-Docker) permite ejecutar comandos de Docker en los jobs.
        image: summerwind/actions-runner-dind
        command: ["/home/runner/run.sh"]