apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner-system

resources:
  - namespace.yaml

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: https://actions-runner-controller.github.io/actions-runner-controller-charts
    releaseName: actions-runner-controller
    version: 0.8.0 # Fijamos versión para estabilidad (ajustar si es necesario)
    namespace: actions-runner-system
    valuesFile: values-controller.yaml
    includeCRDs: true

  - name: gha-runner-scale-set
    repo: https://actions-runner-controller.github.io/actions-runner-controller-charts
    releaseName: swarm-runners-scaleset
    version: 0.8.0
    namespace: actions-runner-system
    valuesFile: values-runner-set.yaml
