# Configuración del RunnerSet (gha-runner-scale-set)
runnerScaleSet:
  # runnerGroup: swarm-runners-scaleset
  minRunners: 1
  maxRunners: 25

githubConfigUrl: "https://github.com/Ka0s-Klaus/ka0s"
githubConfigSecret: controller-manager

controllerServiceAccount:
  name: gha-rs-controller
  namespace: actions-runner-system

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]

# Forzamos los valores a nivel raíz para que Helm los tome si la estructura anterior falla
minRunners: 1
maxRunners: 25
# runnerGroup: swarm-runners
