# Configuración del Controlador (gha-runner-scale-set-controller)
fullnameOverride: gha-rs-controller-ka0s

authSecret:
  name: controller-manager

serviceAccount:
  create: true
  name: gha-rs-controller-ka0s
