# Configuración del Controlador (gha-runner-scale-set-controller)
fullnameOverride: gha-rs-controller

authSecret:
  name: controller-manager

serviceAccount:
  create: true
  name: gha-rs-controller
