# Configuración del RunnerSet (gha-runner-scale-set)
runnerScaleSet:
  # runnerGroup: swarm-runners-scaleset-ka0s
  minRunners: 0
  maxRunners: 5

githubConfigUrl: "https://github.com/Ka0s-Klaus/ka0s"
githubConfigSecret: controller-manager

controllerServiceAccount:
  name: gha-rs-controller-ka0s
  namespace: actions-runner-system

template:
  spec:
    nodeSelector:
      kubernetes.io/hostname: k8-node-20
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]

# Forzamos los valores a nivel raíz para que Helm los tome si la estructura anterior falla
minRunners: 0
maxRunners: 5
# runnerGroup: swarm-runners
