name: 🔄 Cambio (Change)
description: Solicita un cambio controlado y sincronízalo con iTop.
title: "[CHANGE]: <Resumen corto>"
labels: ["itop-change", "change"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los detalles del cambio propuesto. Será mapeado a un Change en iTop.

  - type: input
    id: service
    attributes:
      label: Servicio / CI objetivo
      placeholder: Ej. web-frontend
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción del Cambio
      description: Alcance, ventanas, riesgos.
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Evaluación de Riesgo
      description: Probabilidad e impacto; mitigaciones.

  - type: textarea
    id: backout
    attributes:
      label: Plan de Retroceso
      description: Pasos para revertir en caso de fallo.

