name:  Cambio (Change)
description: Solicita un cambio controlado y sincron铆zalo con iTop.
title: "[CHANGE]: <Resumen corto>"
labels: ["itop-change", "change"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los detalles del cambio propuesto. Ser谩 mapeado a un Change en iTop.

  # Campos obligatorios para la integraci贸n con iTop (Caller, Organization, etc.)
  - type: input
    id: requester
    attributes:
      label: Solicitante
      description: Usuario de GitHub o nombre completo para asignar en iTop.
      placeholder: Nombre o @usuario
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organizaci贸n
      description: Organizaci贸n en iTop (si aplica).
      placeholder: Ej. KA0S
    validations:
      required: true

  - type: dropdown
    id: origin
    attributes:
      label: Origen
      options:
        - portal
        - monitoring
        - phone
        - mail
    validations:
      required: true

  # Detalle del Cambio
  - type: input
    id: service
    attributes:
      label: Servicio / CI objetivo
      placeholder: Ej. web-frontend
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Cambio
      description: Alcance, ventanas, riesgos.
    validations:
      required: true

  # Clasificaci贸n iTop
  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - A person
        - A service
        - A department
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  # Planificaci贸n y Riesgo (para estado Planned)
  - type: textarea
    id: risk
    attributes:
      label: Evaluaci贸n de Riesgo
      description: Probabilidad e impacto; mitigaciones.
    validations:
      required: false

  - type: textarea
    id: backout
    attributes:
      label: Plan de Retroceso
      description: Pasos para revertir en caso de fallo (Fallback plan).
    validations:
      required: false

  - type: input
    id: start_date
    attributes:
      label: Fecha de Inicio Planificada
      placeholder: YYYY-MM-DD HH:MM:SS
    validations:
      required: false

  - type: input
    id: end_date
    attributes:
      label: Fecha de Fin Planificada
      placeholder: YYYY-MM-DD HH:MM:SS
    validations:
      required: false

  - type: dropdown
    id: outage
    attributes:
      label: 驴Implica Corte de Servicio (Outage)?
      options:
        - "no"
        - "yes"
    validations:
      required: false
