name: 游댃 Cambio (Change)
description: Solicita un cambio controlado y sincron칤zalo con iTop.
title: "[CHANGE]: <Resumen corto>"
labels: ["itop-change", "change"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los detalles del cambio propuesto. Ser치 mapeado a un Change en iTop.

  - type: dropdown
    id: organization
    attributes:
      label: Organizacion
      options:
        - Ka0s Inc
        - Test 1
        - Test 2
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Solicitante (Caller)
      placeholder: ka0sc0re

  - type: dropdown
    id: change_type
    attributes:
      label: Tipo de cambio
      options:
        - Routine
        - Normal
        - Emergency

  - type: dropdown
    id: outage
    attributes:
      label: Outage (쯜mplica indisponibilidad del servicio?)
      options:
        - "yes"
        - "no"
    validations:
      required: true

  - type: input
    id: service
    attributes:
      label: Servicio / CI objetivo
      placeholder: Ej. web-frontend
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci칩n del Cambio
      description: Alcance, ventanas, riesgos.
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Evaluaci칩n de Riesgo
      description: Probabilidad e impacto; mitigaciones.

  - type: textarea
    id: backout
    attributes:
      label: Plan de Retroceso
      description: Pasos para revertir en caso de fallo.

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Approved
        - Assigned
        - Closed
        - New
        - Planned
        - Rejected

  - type: input
    id: team
    attributes:
      label: Team
      description: Nombre del equipo en iTop.

  - type: input
    id: agent
    attributes:
      label: Agent
      description: Persona asignada (login o nombre en iTop).

  - type: input
    id: change_manager
    attributes:
      label: Change manager
      description: Responsable de la gesti칩n del cambio.

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - application
        - hardware
        - network
        - other
        - software
        - system

  - type: textarea
    id: reject_reason
    attributes:
      label: Reject reason

  - type: textarea
    id: fallback_plan
    attributes:
      label: Fallback plan

  - type: input
    id: parent_change
    attributes:
      label: Parent change
      description: ID o referencia del cambio padre.

  - type: input
    id: creation_date
    attributes:
      label: Creation date
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: input
    id: start_date
    attributes:
      label: Start date
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: input
    id: end_date
    attributes:
      label: End date
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: input
    id: last_update
    attributes:
      label: Last update
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: input
    id: approval_date
    attributes:
      label: Approval date
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: input
    id: close_date
    attributes:
      label: Close date
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: dropdown
    id: outage
    attributes:
      label: Outage
      options:
        - yes
        - no

