name: 💡 Solicitud de Funcionalidad
description: Sugiere una idea para este proyecto.
title: "[FEATURE]: <Título de la propuesta>"
labels: ["enhancement"]
body:
  - type: textarea
    id: pitch
    attributes:
      label: Descripción de la Propuesta
      description: ¿Qué problema resuelve o qué valor añade?
    validations:
      required: true
