name: 💡 Solicitud de Funcionalidad
description: Sugiere una idea para este proyecto.
title: "[FEATURE]: <Título de la propuesta>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">
          <img src="https://raw.githubusercontent.com/Ka0s-Klaus/ka0s/main/core/imgs/logo-ka0s.png" width="300" />
        </div>

  - type: textarea
    id: pitch
    attributes:
      label: Descripción de la Propuesta
      description: ¿Qué problema resuelve o qué valor añade?
    validations:
      required: true
