name:  Incidencia (Incident)
description: Reporta una incidencia operacional para crear/actualizar un ticket en iTop.
title: "[INCIDENT]: "
labels: ["itop-incident", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los campos para registrar la incidencia. Esta informaci贸n se sincronizar谩 con iTop.

  - type: input
    id: organization
    attributes:
      label: Organizaci贸n
      description: Nombre de la organizaci贸n (ej. MyCompany).
      placeholder: Ka0s Inc
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Solicitante
      description: Email o login del solicitante (debe existir en iTop como Persona).
      placeholder: "@ka0sc0re"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Estado
      options:
        - New
        - Assigned
        - Pending
        - Escalated TTO
        - Escalated TTR
        - Resolved
        - Closed
      default: 0
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - Department
        - Service
        - Person
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: input
    id: service
    attributes:
      label: Servicio / CI afectado
      description: Nombre del servicio o CI impactado.
      placeholder: Ej. web-frontend, DB cluster
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: Explica el s铆ntoma, alcance y condiciones.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos / Evidencias
      description: Adjunta logs, enlaces o pasos de reproducci贸n.
