name: 游뚿 Incidencia (Incident)
description: Reporta una incidencia operacional para crear/actualizar un ticket en iTop.
title: "[INCIDENT]: <Resumen corto>"
labels: ["itop-incident", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los campos para registrar la incidencia. Esta informaci칩n se sincronizar치 con iTop.

  - type: input
    id: service
    attributes:
      label: Servicio / CI afectado
      description: Nombre del servicio o CI impactado.
      placeholder: Ej. web-frontend, DB cluster
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci칩n
      description: Explica el s칤ntoma, alcance y condiciones.
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - Bajo
        - Medio
        - Alto
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - Baja
        - Media
        - Alta
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos / Evidencias
      description: Adjunta logs, enlaces o pasos de reproducci칩n.

