name: 游뚿 Incidencia (Incident)
description: Reporta una incidencia operacional para crear/actualizar un ticket en iTop.
title: "[INCIDENT]: <Resumen corto>"
labels: ["itop-incident", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los campos para registrar la incidencia. Esta informaci칩n se sincronizar치 con iTop.

  # Campos obligatorios para la integraci칩n con iTop
  - type: input
    id: requester
    attributes:
      label: Solicitante
      description: Usuario de GitHub o nombre completo para asignar en iTop.
      placeholder: Nombre o @usuario
    validations:
      required: true

  - type: dropdown
    id: origin
    attributes:
      label: Origen
      options:
        - Portal
        - Monitoring
    validations:
      required: true

  # ==============================
  # Campos Espec칤ficos Zabbix / Trigger
  # ==============================
  - type: input
    id: trigger_name
    attributes:
      label: Trigger Name
      description: "{{TRIGGER.NAME}}"

  - type: input
    id: host_name
    attributes:
      label: Host Name
      description: "{{HOST.NAME}}"

  - type: dropdown
    id: trigger_severity
    attributes:
      label: Trigger Severity
      description: "{{TRIGGER.SEVERITY}}"
      options:
        - Information
        - Warning
        - Average
        - High
        - Disaster

  - type: input
    id: event_datetime
    attributes:
      label: Event Date & Time
      description: "{{EVENT.DATE}} {{EVENT.TIME}}"
      placeholder: "YYYY-MM-DD HH:MM:SS"

  - type: input
    id: event_id
    attributes:
      label: Event ID
      description: "{{EVENT.ID}}"

  - type: input
    id: item_name
    attributes:
      label: Item Name
      description: "{{ITEM.NAME}}"

  - type: input
    id: item_lastvalue
    attributes:
      label: Item Last Value
      description: "{{ITEM.LASTVALUE}}"

  - type: textarea
    id: trigger_description
    attributes:
      label: Trigger Description
      description: "{{TRIGGER.DESCRIPTION}}"

  - type: input
    id: trigger_url
    attributes:
      label: Trigger URL
      description: "{{TRIGGER.URL}}"

  # ==============================
  # Clasificaci칩n iTop
  # ==============================
  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - Bajo
        - Medio
        - Alto
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - Baja
        - Media
        - Alta
    validations:
      required: true


  
