name:  Incidencia (Incident)
description: Reporta una incidencia operacional para crear/actualizar un ticket en iTop.
title: "[INCIDENT]: <Resumen corto>"
labels: ["itop-incident", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Completa los campos para registrar la incidencia. Esta informaci贸n se sincronizar谩 con iTop.

  - type: input
    id: organization
    attributes:
      label: Organizaci贸n
      description: Nombre de la organizaci贸n (ej. MyCompany).
      placeholder: Ka0s Inc
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Solicitante
      description: Email o login del solicitante (debe existir en iTop como Persona).
      placeholder: "@ka0sc0re"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Estado
      options:
        - New
        - Assigned
        - Pending
        - Escalated TTO
        - Escalated TTR
        - Resolved
        - Closed
      default: 0
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - Department
        - Service
        - Person
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Solicitante
      description: Usuario de GitHub o nombre completo para asignar en iTop.
      placeholder: Nombre o @usuario
    validations:
      required: true

  - type: dropdown
    id: origin
    attributes:
      label: Origen
      options:
        - portal
        - monitoring
        - phone
        - mail
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organizaci贸n
      description: Organizaci贸n en iTop (si aplica).
      placeholder: Ej. KA0S
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: Pasos / Evidencias
      description: Adjunta logs, enlaces o pasos de reproducci贸n.
