name: 游뚿 Incidencia (Incident)
description: Reporta una incidencia operacional para crear/actualizar un ticket en iTop.
title: "[INCIDENT]: "
labels: ["itop-incident", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">
          <img src="https://raw.githubusercontent.com/Ka0s-Klaus/ka0s/main/core/imgs/logo-ka0s.png" width="300" />
        </div>

        Completa los campos para registrar la incidencia. Esta informaci칩n se sincronizar치 con iTop.

  - type: dropdown
    id: organization
    attributes:
      label: Organizacion
      options:
        - Ka0s Inc
        - Test 1
        - Test 2
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Solicitante
      description: Email o login del solicitante (debe existir en iTop como Persona).
      placeholder: "@ka0sc0re"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Estado
      options:
        - New
        - Assigned
        - Pending
        - Escalated TTO
        - Escalated TTR
        - Resolved
        - Closed
      default: 0
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - Department
        - Service
        - Person
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: input
    id: service
    attributes:
      label: Servicio / CI afectado
      description: Nombre del servicio o CI impactado.
      placeholder: Ej. web-frontend, DB cluster
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci칩n
      description: Explica el s칤ntoma, alcance y condiciones.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos / Evidencias
      description: Adjunta logs, enlaces o pasos de reproducci칩n.
