name:  Solicitud de Onboarding (Instalaci贸n)
description: Solicita la integraci贸n de tu organizaci贸n o repositorio en el ecosistema Ka0s.
title: "[ONBOARDING]: <Nombre de tu Organizaci贸n/Proyecto>"
labels: ["onboarding", "setup"]
body:
  - type: markdown
    attributes:
      value: |
        ### 隆Bienvenido a Ka0s!
        Gracias por tu inter茅s en adoptar el framework Ka0s. Por favor, completa la siguiente informaci贸n para que nuestro equipo (o nuestros automatas) puedan procesar tu solicitud.

  - type: input
    id: org_name
    attributes:
      label: Nombre de la Organizaci贸n o Proyecto
      description: 驴C贸mo se llama la entidad que adoptar谩 Ka0s?
      placeholder: Ej. Acme Corp
    validations:
      required: true

  - type: input
    id: admin_contact
    attributes:
      label: Contacto Administrativo
      description: Usuario de GitHub o email del responsable t茅cnico.
      placeholder: "@usuario o email@dominio.com"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Tipo de Entorno Objetivo
      options:
        - Kubernetes (Self-Hosted)
        - Kubernetes (Cloud - AWS/GCP/Azure)
        - H铆brido
        - Otro (Especificar en comentarios)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto Adicional
      description: Cu茅ntanos brevemente sobre tu infraestructura actual y qu茅 esperas de Ka0s.
