name: 🧩 Problema (Problem)
description: Declara un problema raíz para su investigación y seguimiento en iTop.
title: "[PROBLEM]: <Resumen corto>"
labels: ["itop-problem", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Usa esta plantilla para problemas raíz que requieren análisis permanente.

  - type: input
    id: related_incidents
    attributes:
      label: Incidencias Relacionadas (URLs o IDs)
      description: Lista de incidencias GitHub/iTop relacionadas.

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: ¿Qué patrón observas? ¿Cuál podría ser la causa raíz?
    validations:
      required: true

  - type: textarea
    id: hypothesis
    attributes:
      label: Hipótesis
      description: Posibles causas o áreas a investigar.

  - type: textarea
    id: plan
    attributes:
      label: Plan de Investigación
      description: Pasos, owners y métricas.

