name: 🛠️ Solicitud de Servicio (Service Request)
description: Pide soporte o una acción estándar; se sincroniza con iTop.
title: "[REQUEST]: "
labels: ["itop-request"]
body:
  - type: markdown
    attributes:
      value: |
        Describe tu solicitud. Se creará/actualizará una UserRequest en iTop.

  - type: dropdown
    id: organization
    attributes:
      label: Organizacion
      options:
        - Ka0s Inc
        - Test 1
        - Test 2
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: Solicitante (si aplica)
      placeholder: "@ka0sc0re"

  - type: dropdown
    id: origin
    attributes:
      label: Origen
      options:
        - Portal
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Detalles de la tarea solicitada.
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impacto
      options:
        - Department
        - Service
        - Person
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgencia
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true
