apiVersion: v1
kind: Secret
metadata:
  name: postgres-ia-secret
  namespace: postgresql-ia
type: Opaque
stringData:
  # In a real scenario, use SealedSecrets or Vault
  # This is a generated default for the vector DB
  POSTGRES_USER: "ka0s_ai"
  POSTGRES_PASSWORD: "change_me_in_production_vector_db_123!"
  POSTGRES_DB: "ka0s_memory"
