apiVersion: v1
kind: Service
metadata:
  name: postgresql-ia
  namespace: postgresql-ia
  labels:
    app: postgresql-ia
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  - port: 10050
    targetPort: 10050
    protocol: TCP
    name: zabbix-agent
  selector:
    app: postgresql-ia
  type: ClusterIP
