name: "[Ka0s] Template Workflow" # Estandarizar nombre: [Ka0s] <Nombre Descriptivo>

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Motivo de la ejecución manual'
        required: false
        default: 'Mantenimiento manual'
  push:
    branches:
      - main
    paths:
      - 'core/**' # Ajustar al alcance del workflow

permissions:
  contents: write # Requerido para commits automáticos (audit logs, reportes)
  issues: write   # Requerido para notificar en issues
  actions: read   # Requerido para llamar a otros workflows/actions

env:
  KAOS_MODULE: "[Ka0S] Template" # Nombre del módulo para logs
  KAOS_CORRELATION_ID: ${{ github.run_id }}
  KAOS_ACTOR: ${{ github.actor }}

jobs:
  # -----------------------------------------------------------------------------
  # JOB 1: CORE EXECUTION
  # Lógica principal del workflow.
  # -----------------------------------------------------------------------------
  core-execution:
    name: Core Execution
    runs-on: swarm-runners-scaleset # Estándar de runners en Ka0s
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para git diff y análisis de historia

      - name: Setup Environment
        run: |
          echo "Iniciando módulo: ${{ env.KAOS_MODULE }}"
          echo "Run ID: ${{ env.KAOS_CORRELATION_ID }}"
          echo "Actor: ${{ env.KAOS_ACTOR }}"

      # [BLOQUE PERSONALIZABLE] Lógica del workflow
      - name: Main Logic
        run: |
          echo "Ejecutando lógica principal..."
          # ./ruta/a/script.sh

      # [OPCIONAL] Commit de resultados/evidencias
      - name: Commit & Push Results
        if: success() # Solo si la lógica anterior tuvo éxito
        run: |
          git config --global user.name "${{ secrets.KAOS_BOT_NAME || 'Ka0s Bot' }}"
          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL || 'bot@ka0s.io' }}"
          
          # Ajustar ruta de archivos a commitear
          # git add audit/outputs/
          
          if ! git diff --staged --quiet; then
            git commit -m "chore(ka0s): update artifacts ${{ env.KAOS_MODULE }} run ${{ env.KAOS_CORRELATION_ID }} [skip ci]"
            # Reintento básico de push para evitar conflictos de concurrencia
            count=0
            until git push origin HEAD:${{ github.ref_name }} || [ $count -eq 5 ]; do
              echo "Push fallido, reintentando..."
              git pull --rebase origin ${{ github.ref_name }}
              ((count++))
              sleep 2
            done
          else
            echo "No hay cambios para subir."
          fi

  # -----------------------------------------------------------------------------
  # JOB 2: HANDLE SUCCESS (Opcional)
  # Notificaciones o limpieza en caso de éxito.
  # -----------------------------------------------------------------------------
  handle-success:
    name: Handle Success
    needs: [core-execution]
    if: success()
    runs-on: swarm-runners-scaleset
    steps:
      - name: Notify Success
        run: echo "✅ Workflow ${{ env.KAOS_MODULE }} completado correctamente."

  # -----------------------------------------------------------------------------
  # JOB 3: HANDLE FAILURE (Opcional)
  # Notificaciones o limpieza en caso de error.
  # -----------------------------------------------------------------------------
  handle-failure:
    name: Handle Failure
    needs: [core-execution]
    if: failure()
    runs-on: swarm-runners-scaleset
    steps:
      - name: Notify Failure
        run: echo "❌ Workflow ${{ env.KAOS_MODULE }} falló. Revisar logs."

  # -----------------------------------------------------------------------------
  # JOB 4: END WORKFLOW (Opcional/Estándar)
  # Acciones finales: Notificaciones a Issues, Trigger de Inspector, Limpieza global.
  # Basado en el estándar de .github/workflows/kaos.yml
  # -----------------------------------------------------------------------------
  end-workflow:
    name: End Workflow
    runs-on: swarm-runners-scaleset
    needs: [core-execution, handle-success, handle-failure]
    if: always() # Se ejecuta siempre para garantizar cierre
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Instalar GH CLI si es necesario (Descomentar si el runner no lo tiene)
      # - name: Install GH CLI
      #   uses: ./.github/actions/install-gh-cli

      - name: Finalize Process
        run: |
          echo "Finalizando proceso ${{ env.KAOS_MODULE }}..."
          
          # Extracción del número de issue desde la rama (convención H*, F*, etc.)
          RNNUMBER=$(echo "${{ github.ref_name }}" | grep -o '[0-9]*' || true)
          
          if [ -n "$RNNUMBER" ]; then
            echo "Notificando a Issue #$RNNUMBER..."
            gh issue comment $RNNUMBER --body "Se finaliza ${{ env.KAOS_MODULE }} - Run ID: ${{ env.KAOS_CORRELATION_ID }}"
            
            # Disparar Inspector (Auditoría) - Descomentar si aplica
            # echo "Disparando Inspector..."
            # gh workflow run inspector.yml --ref 'main' \
            #   -f kaos-issue-id="$RNNUMBER" \
            #   -f kaos-workflow-id="${{ env.KAOS_CORRELATION_ID }}" \
            #   -f kaos-user-start="${{ env.KAOS_ACTOR }}"
          else
             echo "No se detectó número de issue en la referencia ${{ github.ref_name }}."
          fi
