name: Ka0s Workflow Base Template

on:
  workflow_dispatch:
    inputs:
      example-input:
        description: "Ejemplo de entrada para el workflow"
        required: false
        default: ""
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.json'
      - '**.md'
      - '**.py'
      - '**.js'
      - '**.html'
    branches:
      - 'main'
      - 'H*'
      - 'F*'
      - 'RN*'
  schedule:
    - cron: '0 0 * * *' # Ejemplo: ejecución diaria a medianoche

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  KAOS_CODE: ${{ github.run_id }}
  KAOS_MODULE: "[Ka0S] Base Workflow"
  KAOS_PATH_RESUME: "audit/kaos/"
  KAOS_ACTOR: ${{ github.actor }}

jobs:
  job-core:
    name: "Core Job"
    runs-on:
      group: ka0s
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - name: Setup Environment
        run: |
          echo "Configurando entorno..."
      - name: Main Execution
        run: |
          echo "Ejecutando proceso principal..."
      - name: Upload Results
        run: |
          echo "Subiendo resultados..."
          git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
          git pull --rebase
          git add *
          git commit -m "[Ka0S] Subiendo archivos de resultado de ejecución..." || echo "Sin cambios para subir"
          git push origin ${{ github.ref }} --force-with-lease

  handle-success:
    name: "Handle Success"
    runs-on:
      group: ka0s
    needs: [job-core]
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - name: Success Message
        run: |
          echo "Proceso finalizado correctamente."
          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
          gh issue comment $RNNUMBER --body "El proceso ha finalizado correctamente ${{ env.KAOS_CODE }}."

  handle-failure:
    name: "Handle Failure"
    runs-on:
      group: ka0s
    needs: [job-core]
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - name: Failure Message
        run: |
          echo "Error detectado en el proceso."
          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
          gh issue comment $RNNUMBER --body "El proceso no ha finalizado correctamente ${{ env.KAOS_CODE }}."

  end-workflow:
    name: "End Workflow"
    runs-on:
      group: ka0s
    needs: [job-core, handle-success, handle-failure]
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - name: End Message
        run: |
          echo "Finalizando workflow..."
          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
          gh issue comment $RNNUMBER --body "Se finaliza Ka0s ${{ env.KAOS_CODE }}"
          gh workflow run inspector.yml --ref 'main' -f kaos-issue-id=$RNNUMBER -f kaos-workflow-id="${{ env.KAOS_CODE }}" -f kaos-user-start=""
