apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-03-12T07:12:23Z"
  name: ollama
  namespace: ollama
  resourceVersion: "19546506"
  uid: 4e723249-31dc-47c8-8bac-7183c1e85a62
subsets:
- addresses:
  - ip: 172.16.74.5
    nodeName: k8-manager
    targetRef:
      kind: Pod
      name: ollama-5bb8fddf7c-hbscd
      namespace: ollama
      uid: 8a458a56-c42a-47f9-a6f0-f7884b1c005f
  ports:
  - name: http
    port: 11434
    protocol: TCP
