apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"name":"ollama","namespace":"ollama"},"spec":{"ports":[{"name":"http","port":11434,"targetPort":11434}],"selector":{"app":"ollama"},"type":"ClusterIP"}}
  creationTimestamp: "2026-03-12T07:12:23Z"
  name: ollama
  namespace: ollama
  resourceVersion: "19547636"
  uid: 06d2e112-7cca-4982-9b05-6a5ad4828049
spec:
  clusterIP: 10.103.245.188
  clusterIPs:
  - 10.103.245.188
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
