apiVersion: batch/v1
kind: Job
metadata:
  name: fix-mysql-permissions
  namespace: itop
  labels:
    app: mysql-fix
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: fix-permissions
        image: mysql:5.7
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Waiting for MySQL to be ready..."
            # Wait loop to ensure DB is up
            until mysql -h mysql -u root -padmin -e "SELECT 1"; do
              echo "MySQL not ready, sleeping 5s..."
              sleep 5
            done
            echo "MySQL is ready. Granting global privileges to 'admin'..."
            mysql -h mysql -u root -padmin -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%'; FLUSH PRIVILEGES;"
            echo "Permissions granted successfully."
      restartPolicy: OnFailure
