apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itop-web-pvc
  namespace: itop
  labels:
    app: itop
    core.kaos.io/type: finops
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: itop-web-pv