apiVersion: v1
kind: Service
metadata:
  name: itop
  namespace: itop
  labels:
    app: itop
    core.kaos.io/type: finops
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: itop
