apiVersion: v1
kind: ConfigMap
metadata:
  name: itop-nginx-config
  namespace: itop
  labels:
    app: itop
    core.kaos.io/type: finops
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 8443 ssl;
        server_name _;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://localhost:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
