name: GitHub Stats Collector

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecución diaria a medianoche
  workflow_dispatch:     # Ejecución manual permitida

env:

permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read


jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pymongo requests python-dotenv

    - name: Run Stats Collector
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        ORG_NAME: ${{ vars.ORG_NAME }}  # Configura en repo settings > Variables
        REPO_NAME: ${{ vars.REPO_NAME }}
      run: python scripts/github_stats.py