apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  AUTH_GITHUB_CLIENT_ID: Ov23liroa9gmpWr6KLop
  AUTH_GITHUB_CLIENT_SECRET: 8045a8eec80aba2b27e359b5060cc6b2e7d3c6ef
