apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
    core.kaos.io/type: catalog
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 8082
      targetPort: 8443
      protocol: TCP
      name: https-custom
  selector:
    app: backstage
