apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      title: Kaos Backstage
      baseUrl: http://83.32.50.24:8082

    backend:
      baseUrl: http://83.32.50.24:8082
      listen: 0.0.0.0:7007
      csp:
        upgradeInsecureRequests: false
      cors:
        origin: http://83.32.50.24:8082
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: postgresql
          port: 5432
          user: backstage
          password: backstage
