apiVersion: v1
kind: PersistentVolume
metadata:
  name: backstage-postgresql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/backstage/postgresql"
