apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-postgresql-pvc
  namespace: backstage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
