apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-certs-generator
  namespace: soc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wazuh-certs-manager
  namespace: soc
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wazuh-certs-generator-binding
  namespace: soc
subjects:
  - kind: ServiceAccount
    name: wazuh-certs-generator
    namespace: soc
roleRef:
  kind: Role
  name: wazuh-certs-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-certs-gen-config
  namespace: soc
data:
  config.yml: |
    nodes:
      indexer:
        - name: wazuh-indexer
          ip: "wazuh-indexer"
        - name: wazuh-indexer-svc
          ip: "wazuh-indexer.soc.svc"
        - name: wazuh-indexer-0
          ip: "wazuh-indexer-0.wazuh-indexer-headless.soc.svc.cluster.local"
      server:
        - name: wazuh-manager
          ip: "wazuh-manager"
        - name: wazuh-manager-svc
          ip: "wazuh-manager.soc.svc"
        - name: wazuh-manager-worker-0
          ip: "wazuh-manager-worker-0.wazuh-manager-worker.soc.svc.cluster.local"
      dashboard:
        - name: wazuh-dashboard
          ip: "wazuh-dashboard"
        - name: wazuh-dashboard-svc
          ip: "wazuh-dashboard.soc.svc"

  run.sh: |
    #!/bin/bash
    set -e
    
    SECRET_NAME="wazuh-indexer-certs"
    NAMESPACE="soc"
    
    # Instalación de dependencias mínimas
    echo "Installing dependencies..."
    apt-get update && apt-get install -y curl openssl tar ca-certificates
    
    # Instalar kubectl
    echo "Installing kubectl..."
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/
    
    # Verificar si los secretos ya existen para evitar sobrescribir (idempotencia)
    if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" > /dev/null 2>&1; then
      echo "✅ Secrets already exist. Skipping generation to preserve CA trust."
      # Opcional: Podríamos implementar lógica de rotación aquí si fuera necesario
      exit 0
    fi
    
    echo "🚀 Generating new Wazuh certificates..."
    
    WORKDIR="/tmp/certs-gen"
    mkdir -p "$WORKDIR"
    cd "$WORKDIR"
    
    # Descargar herramienta oficial
    curl -sO https://packages.wazuh.com/4.14/wazuh-certs-tool.sh
    chmod +x wazuh-certs-tool.sh
    
    # Copiar config desde ConfigMap
    cp /config/config.yml .
    
    # Ejecutar herramienta
    ./wazuh-certs-tool.sh -A
    
    echo "📦 Creating Kubernetes Secrets..."
    
    # Indexer Secret
    kubectl create secret generic wazuh-indexer-certs \
      --from-file=root-ca.pem=wazuh-certificates/root-ca.pem \
      --from-file=indexer.pem=wazuh-certificates/wazuh-indexer.pem \
      --from-file=indexer-key.pem=wazuh-certificates/wazuh-indexer-key.pem \
      --from-file=admin.pem=wazuh-certificates/admin.pem \
      --from-file=admin-key.pem=wazuh-certificates/admin-key.pem \
      -n "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
    
    # Manager Secret
    kubectl create secret generic wazuh-manager-certs \
      --from-file=root-ca.pem=wazuh-certificates/root-ca.pem \
      --from-file=manager.pem=wazuh-certificates/wazuh-manager.pem \
      --from-file=manager-key.pem=wazuh-certificates/wazuh-manager-key.pem \
      -n "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
    
    # Dashboard Secret
    kubectl create secret generic wazuh-dashboard-certs \
      --from-file=root-ca.pem=wazuh-certificates/root-ca.pem \
      --from-file=dashboard.pem=wazuh-certificates/wazuh-dashboard.pem \
      --from-file=dashboard-key.pem=wazuh-certificates/wazuh-dashboard-key.pem \
      -n "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
      
    echo "🎉 Certificates generated and secrets created successfully!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-certs-generator
  namespace: soc
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: wazuh-certs-generator
      containers:
      - name: generator
        image: ubuntu:22.04
        command: ["/bin/bash", "/config/run.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
      restartPolicy: OnFailure
      volumes:
      - name: config-volume
        configMap:
          name: wazuh-certs-gen-config
