apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-certs-config
  namespace: soc
data:
  instances.yml: |
    nodes:
      indexer:
        - name: wazuh-indexer
          ip: 127.0.0.1
          dns:
            - wazuh-indexer
            - wazuh-indexer.soc.svc
            - wazuh-indexer.soc.svc.cluster.local
      server:
        - name: wazuh-manager
          ip: 127.0.0.1
          dns:
            - wazuh-manager
            - wazuh-manager.soc.svc
            - wazuh-manager.soc.svc.cluster.local
      dashboard:
        - name: wazuh-dashboard
          ip: 127.0.0.1
          dns:
            - wazuh-dashboard
            - wazuh-dashboard.soc.svc
            - wazuh-dashboard.soc.svc.cluster.local
            - soc.ka0s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-certs-generator
  namespace: soc
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: wazuh-certs-sa
      containers:
        - name: cert-generator
          image: ubuntu:22.04
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              echo ">>> Wazuh Certs Generator (Official Tool) <<<"
              
              apt-get update && apt-get install -y curl openssl tar bash ca-certificates
              
              # Install kubectl
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/kubectl
              
              # Get Wazuh Certs Tool
              curl -sO https://packages.wazuh.com/4.14/wazuh-certs-tool.sh
              chmod +x wazuh-certs-tool.sh
              
              # Prepare config
              cp /config/instances.yml ./config.yml
              
              echo "Generating certificates..."
              ./wazuh-certs-tool.sh -A
              
              echo "Processing output..."
              tar -xf wazuh-certificates.tar -C /tmp/
              
              # Verify files exist
              ls -l /tmp/wazuh-certificates/
              
              # Update Kubernetes Secrets
              echo "Updating Kubernetes Secrets..."
              
              # 1. Indexer
              kubectl delete secret wazuh-indexer-certs -n soc --ignore-not-found
              kubectl create secret generic wazuh-indexer-certs -n soc \
                --from-file=root-ca.pem=/tmp/wazuh-certificates/root-ca.pem \
                --from-file=indexer.pem=/tmp/wazuh-certificates/wazuh-indexer.pem \
                --from-file=indexer-key.pem=/tmp/wazuh-certificates/wazuh-indexer-key.pem \
                --from-file=admin.pem=/tmp/wazuh-certificates/admin.pem \
                --from-file=admin-key.pem=/tmp/wazuh-certificates/admin-key.pem
                
              # 2. Manager
              kubectl delete secret wazuh-manager-certs -n soc --ignore-not-found
              kubectl create secret generic wazuh-manager-certs -n soc \
                --from-file=root-ca.pem=/tmp/wazuh-certificates/root-ca.pem \
                --from-file=manager.pem=/tmp/wazuh-certificates/wazuh-manager.pem \
                --from-file=manager-key.pem=/tmp/wazuh-certificates/wazuh-manager-key.pem \
                --from-file=admin.pem=/tmp/wazuh-certificates/admin.pem \
                --from-file=admin-key.pem=/tmp/wazuh-certificates/admin-key.pem
                
              # 3. Dashboard
              kubectl delete secret wazuh-dashboard-certs -n soc --ignore-not-found
              kubectl create secret generic wazuh-dashboard-certs -n soc \
                --from-file=root-ca.pem=/tmp/wazuh-certificates/root-ca.pem \
                --from-file=dashboard.pem=/tmp/wazuh-certificates/wazuh-dashboard.pem \
                --from-file=dashboard-key.pem=/tmp/wazuh-certificates/wazuh-dashboard-key.pem
                
              echo "Secrets updated successfully!"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: wazuh-certs-config
      restartPolicy: OnFailure
