apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-certs-generator-v9
  namespace: soc
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: wazuh-certs-sa
      containers:
        - name: cert-generator
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo ">>> Wazuh Cert Generator v9 (Alpine) <<<"
              
              echo "Installing dependencies..."
              apk add --no-cache openssl curl bash
              
              echo "Installing kubectl..."
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/kubectl
              
              mkdir -p /tmp/certs
              cd /tmp/certs
              
              # 1. Root CA
              echo "Generating Root CA..."
              openssl genrsa -out root-ca.key 4096
              openssl req -x509 -new -nodes -key root-ca.key -sha256 -days 3650 \
                -subj "/C=US/L=California/O=Wazuh/CN=Wazuh Root CA" -out root-ca.pem
              
              # 2. Admin Cert
              echo "Generating Admin Cert..."
              openssl genrsa -out admin-key-temp.pem 2048
              openssl pkcs8 -topk8 -inform PEM -outform PEM -in admin-key-temp.pem -out admin-key.pem -nocrypt
              openssl req -new -key admin-key.pem -out admin.csr -subj "/C=US/L=California/O=Wazuh/CN=admin"
              openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca.key -CAcreateserial \
                -out admin.pem -days 3650 -sha256
              
              # 3. Indexer Cert
              echo "Generating Indexer Cert..."
              openssl genrsa -out indexer-key-temp.pem 2048
              openssl pkcs8 -topk8 -inform PEM -outform PEM -in indexer-key-temp.pem -out indexer-key.pem -nocrypt
              openssl req -new -key indexer-key.pem -out indexer.csr -subj "/C=US/L=California/O=Wazuh/CN=wazuh-indexer"
              echo "subjectAltName=DNS:wazuh-indexer,DNS:wazuh-indexer.soc.svc,DNS:localhost,IP:127.0.0.1" > indexer.ext
              openssl x509 -req -in indexer.csr -CA root-ca.pem -CAkey root-ca.key -CAcreateserial \
                -out indexer.pem -days 3650 -sha256 -extfile indexer.ext
              
              # 4. Manager Cert
              echo "Generating Manager Cert..."
              openssl genrsa -out manager-key-temp.pem 2048
              openssl pkcs8 -topk8 -inform PEM -outform PEM -in manager-key-temp.pem -out manager-key.pem -nocrypt
              openssl req -new -key manager-key.pem -out manager.csr -subj "/C=US/L=California/O=Wazuh/CN=wazuh-manager"
              echo "subjectAltName=DNS:wazuh-manager,DNS:wazuh-manager.soc.svc,DNS:localhost,IP:127.0.0.1" > manager.ext
              openssl x509 -req -in manager.csr -CA root-ca.pem -CAkey root-ca.key -CAcreateserial \
                -out manager.pem -days 3650 -sha256 -extfile manager.ext
              
              # 5. Dashboard Cert
              echo "Generating Dashboard Cert..."
              openssl genrsa -out dashboard-key-temp.pem 2048
              openssl pkcs8 -topk8 -inform PEM -outform PEM -in dashboard-key-temp.pem -out dashboard-key.pem -nocrypt
              openssl req -new -key dashboard-key.pem -out dashboard.csr -subj "/C=US/L=California/O=Wazuh/CN=wazuh-dashboard"
              echo "subjectAltName=DNS:wazuh-dashboard,DNS:wazuh-dashboard.soc.svc,DNS:soc.ka0s.io,DNS:localhost,IP:127.0.0.1" > dashboard.ext
              openssl x509 -req -in dashboard.csr -CA root-ca.pem -CAkey root-ca.key -CAcreateserial \
                -out dashboard.pem -days 3650 -sha256 -extfile dashboard.ext
              
              # Create Secrets
              echo "Creating Secrets..."
              
              # Indexer Secret
              kubectl delete secret wazuh-indexer-certs -n soc --ignore-not-found
              kubectl create secret generic wazuh-indexer-certs -n soc \
                --from-file=root-ca.pem=root-ca.pem \
                --from-file=indexer.pem=indexer.pem \
                --from-file=indexer-key.pem=indexer-key.pem \
                --from-file=admin.pem=admin.pem \
                --from-file=admin-key.pem=admin-key.pem
              
              # Manager Secret
              kubectl delete secret wazuh-manager-certs -n soc --ignore-not-found
              kubectl create secret generic wazuh-manager-certs -n soc \
                --from-file=root-ca.pem=root-ca.pem \
                --from-file=manager.pem=manager.pem \
                --from-file=manager-key.pem=manager-key.pem \
                --from-file=admin.pem=admin.pem \
                --from-file=admin-key.pem=admin-key.pem
              
              # Dashboard Secret
              kubectl delete secret wazuh-dashboard-certs -n soc --ignore-not-found
              kubectl create secret generic wazuh-dashboard-certs -n soc \
                --from-file=root-ca.pem=root-ca.pem \
                --from-file=dashboard.pem=dashboard.pem \
                --from-file=dashboard-key.pem=dashboard-key.pem
              
              echo "Secrets created successfully!"
      restartPolicy: OnFailure
