apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  namespace: soc
  labels:
    app: wazuh-manager
spec:
  ports:
    - port: 1514
      name: agents
      targetPort: 1514
    - port: 1515
      name: registration
      targetPort: 1515
    - port: 55000
      name: api
      targetPort: 55000
  selector:
    app: wazuh-manager
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
  namespace: soc
  labels:
    app: wazuh-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.14.2
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 1514
              name: agents
            - containerPort: 1515
              name: registration
            - containerPort: 55000
              name: api
          env:
            - name: INDEXER_URL
              value: "https://wazuh-indexer:9200"
            - name: INDEXER_USERNAME
              value: "admin"
            - name: INDEXER_PASSWORD
              value: "admin"
          volumeMounts:
            - name: wazuh-manager-data
              mountPath: /var/ossec/data
            - name: wazuh-manager-certs
              mountPath: /etc/filebeat/certs/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: wazuh-manager-certs
              mountPath: /etc/filebeat/certs/filebeat.pem
              subPath: manager.pem
              readOnly: true
            - name: wazuh-manager-certs
              mountPath: /etc/filebeat/certs/filebeat-key.pem
              subPath: manager-key.pem
              readOnly: true
            - name: wazuh-manager-certs
              mountPath: /var/ossec/etc/sslmanager.cert
              subPath: manager.pem
              readOnly: true
            - name: wazuh-manager-certs
              mountPath: /var/ossec/etc/sslmanager.key
              subPath: manager-key.pem
              readOnly: true
      volumes:
        - name: wazuh-manager-data
          persistentVolumeClaim:
            claimName: wazuh-manager-data-v2
        - name: wazuh-manager-certs
          secret:
            secretName: wazuh-manager-certs
            defaultMode: 420
