apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: soc
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: config-init
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              echo "Detecting interface..."
              # Try detecting interface via default route
              IFACE=$(ip route get 8.8.8.8 2>/dev/null | awk '{print $5;exit}')
              if [ -z "$IFACE" ]; then
                IFACE=$(ip route get 1 2>/dev/null | awk '{print $5;exit}')
              fi
              
              if [ -z "$IFACE" ]; then
                 echo "Warning: Could not detect interface via route. Listing available interfaces:"
                 ip link
                 # Fallback to first non-loopback
                 IFACE=$(ip -o link show | awk -F': ' '{print $2}' | grep -v "lo" | head -n 1)
              fi

              if [ -z "$IFACE" ]; then
                echo "Error: No interface found. Defaulting to eth0."
                IFACE="eth0"
              else
                echo "Detected interface: $IFACE"
              fi
              
              # Save interface for Suricata
              echo "$IFACE" > /config/interface

              echo "Generating Suricata config..."
              sed "s/interface: eth0/interface: $IFACE/g" /template/suricata.yaml > /config/suricata.yaml
              
              echo "Config verification:"
              grep "interface:" /config/suricata.yaml
          volumeMounts:
            - name: suricata-conf
              mountPath: /template
            - name: shared-config
              mountPath: /config
      containers:
        # Wazuh Agent Container
        - name: wazuh-agent
          image: wazuh/wazuh-agent:4.14.2
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Injecting ossec.conf..."
              cp /tmp/wazuh-config/ossec.conf /var/ossec/etc/ossec.conf
              echo "Starting Wazuh Agent..."
              exec /init
          env:
            - name: WAZUH_MANAGER
              value: "wazuh-manager.soc.svc"
            - name: WAZUH_AGENT_GROUP
              value: "default"
          volumeMounts:
            - name: wazuh-agent-conf
              mountPath: /tmp/wazuh-config/ossec.conf
              subPath: ossec.conf
            - name: var-log
              mountPath: /host/var/log
              readOnly: true
            - name: suricata-logs
              mountPath: /var/log/suricata
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        # Suricata Sidecar Container
        - name: suricata
          image: jasonish/suricata:latest
          command: ["sh", "-c"]
          args:
            - |
              IFACE=$(cat /etc/suricata-shared/interface)
              echo "Starting Suricata on interface $IFACE..."
              if [ ! -f /etc/suricata-shared/suricata.yaml ]; then
                echo "Error: Configuration file not found!"
                ls -l /etc/suricata-shared/
                exit 1
              fi
              
              # Optional rule update - non-blocking
              if command -v suricata-update > /dev/null; then
                  echo "Updating rules..."
                  suricata-update || echo "Rule update failed, proceeding with existing rules"
              fi
              
              echo "Launching Suricata..."
              exec /usr/bin/suricata -c /etc/suricata-shared/suricata.yaml -i "$IFACE"
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "SYS_NICE"]
          volumeMounts:
            - name: shared-config
              mountPath: /etc/suricata-shared
              readOnly: true
            - name: suricata-logs
              mountPath: /var/log/suricata
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: wazuh-agent-conf
          configMap:
            name: wazuh-agent-conf
        - name: suricata-conf
          configMap:
            name: suricata-conf
        - name: shared-config
          emptyDir: {}
        - name: var-log
          hostPath:
            path: /var/log
        - name: suricata-logs
          emptyDir: {}
