apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-security-init-v4
  namespace: soc
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: security-init
          image: wazuh/wazuh-indexer:4.14.2
          env:
            - name: OPENSEARCH_JAVA_HOME
              value: /usr/share/wazuh-indexer/jdk
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              export JAVA_HOME=/usr/share/wazuh-indexer/jdk
              export PATH=$JAVA_HOME/bin:$PATH
              
              echo ">>> DIAGNOSTICS <<<"
              echo "Checking CA cert details:"
              openssl x509 -in /usr/share/wazuh-indexer/config/certs/root-ca.pem -noout -subject -issuer -dates
              
              echo "Checking Admin cert details:"
              openssl x509 -in /usr/share/wazuh-indexer/config/certs/admin.pem -noout -subject -issuer -dates
              
              echo "Checking Server Cert (via openssl):"
              # Try to connect and show cert info. Using IP to avoid DNS issues if any, but using Service DNS here.
              # echo "Q" to exit s_client
              echo "Q" | openssl s_client -connect wazuh-indexer.soc.svc:9300 -showcerts 2>/dev/null | openssl x509 -noout -subject -issuer -dates || echo "OpenSSL check failed or timed out"
              
              echo "Running securityadmin.sh..."
              /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh \
                -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ \
                -icl -nhnv \
                -cacert /usr/share/wazuh-indexer/config/certs/root-ca.pem \
                -cert /usr/share/wazuh-indexer/config/certs/admin.pem \
                -key /usr/share/wazuh-indexer/config/certs/admin-key.pem \
                -h wazuh-indexer.soc.svc \
                -p 9300
          volumeMounts:
            - name: certificates
              mountPath: /usr/share/wazuh-indexer/config/certs
              readOnly: true
      volumes:
        - name: certificates
          secret:
            secretName: wazuh-indexer-certs
      restartPolicy: OnFailure
