apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-security-init-v3
  namespace: soc
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: security-init
          image: wazuh/wazuh-indexer:4.14.2
          env:
            - name: OPENSEARCH_JAVA_HOME
              value: /usr/share/wazuh-indexer/jdk
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              echo ">>> Starting Security Init V3 <<<"
              echo "Checking JDK path..."
              if [ -d "$OPENSEARCH_JAVA_HOME" ]; then
                echo "JDK found at $OPENSEARCH_JAVA_HOME"
                ls -ld $OPENSEARCH_JAVA_HOME
              else
                echo "ERROR: JDK path $OPENSEARCH_JAVA_HOME not found!"
                # Fallback check
                ls -d /usr/share/wazuh-indexer/jdk* || echo "No JDK found in /usr/share/wazuh-indexer/"
              fi
              
              # Force PATH and JAVA_HOME
              export JAVA_HOME=$OPENSEARCH_JAVA_HOME
              export PATH=$JAVA_HOME/bin:$PATH
              
              echo "Java version check:"
              java -version || echo "Java command not working"
              
              echo "Waiting for Indexer to be ready..."
              until curl -s -k https://wazuh-indexer:9200; do sleep 5; done
              
              echo "Running securityadmin.sh..."
              /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh \
                -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ \
                -icl -nhnv \
                -cacert /usr/share/wazuh-indexer/config/certs/root-ca.pem \
                -cert /usr/share/wazuh-indexer/config/certs/admin.pem \
                -key /usr/share/wazuh-indexer/config/certs/admin-key.pem \
                -h wazuh-indexer.soc.svc \
                -p 9300
          volumeMounts:
            - name: certificates
              mountPath: /usr/share/wazuh-indexer/config/certs
              readOnly: true
      volumes:
        - name: certificates
          secret:
            secretName: wazuh-indexer-certs
      restartPolicy: OnFailure
