apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-security-init-v13
  namespace: soc
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: security-init
          image: wazuh/wazuh-indexer:4.14.2
          env:
            - name: OPENSEARCH_JAVA_HOME
              value: /usr/share/wazuh-indexer/jdk
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              export JAVA_HOME=/usr/share/wazuh-indexer/jdk
              export PATH=$JAVA_HOME/bin:$PATH
              
              echo ">>> Wazuh Security Init <<<"
              echo "Checking admin cert..."
              ls -l /usr/share/wazuh-indexer/config/certs/admin.pem
              
              echo "Waiting 60s for Indexer stability..."
              sleep 60
              
              echo "Waiting for Indexer port 9200..."
              until curl -s -k https://wazuh-indexer.soc.svc:9200; do 
                echo "Waiting for 9200..."
                sleep 5
              done
              echo "Indexer 9200 is UP."
              
              echo "Running securityadmin.sh loop..."
              RETRIES=10
              for i in $(seq 1 $RETRIES); do
                echo "Attempt $i/$RETRIES..."
                /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh \
                  -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ \
                  -icl -nhnv \
                  -cacert /usr/share/wazuh-indexer/config/certs/root-ca.pem \
                  -cert /usr/share/wazuh-indexer/config/certs/admin.pem \
                  -key /usr/share/wazuh-indexer/config/certs/admin-key.pem \
                  -h wazuh-indexer.soc.svc \
                  -p 9300 && echo "Security Init SUCCESS" && exit 0
                
                echo "Attempt $i failed. Sleeping 15s..."
                sleep 15
              done
              
              echo "Security Init FAILED after $RETRIES attempts."
              exit 1
          volumeMounts:
            - name: certificates
              mountPath: /usr/share/wazuh-indexer/config/certs
              readOnly: true
      volumes:
        - name: certificates
          secret:
            secretName: wazuh-indexer-certs
      restartPolicy: OnFailure
