apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-agent
  namespace: wazuh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wazuh-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wazuh-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wazuh-agent
subjects:
- kind: ServiceAccount
  name: wazuh-agent
  namespace: wazuh
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      serviceAccountName: wazuh-agent
      containers:
      - name: wazuh-agent
        image: wazuh/wazuh-agent:4.14.1
        env:
        - name: WAZUH_MANAGER_HOST
          value: "wazuh-manager"
        volumeMounts:
        - name: run
          mountPath: /var/run
        - name: var-ossec
          mountPath: /var/ossec
        - name: etc-ossec
          mountPath: /etc/ossec
      volumes:
      - name: run
        hostPath:
          path: /var/run
      - name: var-ossec
        hostPath:
          path: /var/ossec
      - name: etc-ossec
        hostPath:
          path: /etc/ossec