apiVersion: v1
kind: Service
metadata:
  name: wazuh-external
  namespace: soc
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wazuh-external
  namespace: soc
subsets:
- addresses:
  - ip: 192.168.1.40
  ports:
  - name: https
    port: 443
    protocol: TCP
