apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: wazuh
  labels:
    app: wazuh-indexer
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
  selector:
    app: wazuh-indexer