apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  ports:
  - name: api
    port: 55000
    protocol: TCP
  - name: registration
    port: 1514
    protocol: TCP
  - name: reporting
    port: 1515
    protocol: TCP
  selector:
    app: wazuh-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
      - name: wazuh-manager
        image: wazuh/wazuh-manager:4.14.1
        ports:
        - containerPort: 55000
          name: api
        - containerPort: 1514
          name: registration
        - containerPort: 1515
          name: reporting
        env:
        - name: WAZUH_INDEXER_URL
          value: "https://wazuh-indexer:9200"
        - name: WAZUH_INDEXER_USER
          value: "admin"
        - name: WAZUH_INDEXER_PASSWORD
          value: "admin"