apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-pvc
  namespace: soc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
