apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    name: mongo
  - port: 10050
    name: zabbix-agent
  type: ClusterIP
  selector:
    app: mongo