apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        startupProbe:
          tcpSocket:
            port: 27017
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:ubuntu-7.0-latest
        ports:
        - containerPort: 10050
          name: zabbix-agent
        env:
        - name: ZBX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZBX_SERVER_HOST
          value: "zabbix-server.zabbix.svc.cluster.local"
        - name: ZBX_METADATA
          value: "mongo"
        - name: ZBX_PLUGINS_MONGODB_SESSIONS_DEFAULT_URI
          value: "tcp://localhost:27017"
        - name: ZBX_PLUGINS_MONGODB_SESSIONS_DEFAULT_USER
          value: "root"
        - name: ZBX_PLUGINS_MONGODB_SESSIONS_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 8Gi