##mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  mongo-root-password: "dnFoZFc4ZU1SSGpXM0kzUlhaak5VQTlCNUVVcGpBUlhmYVhqR3hHbkFucz0="