apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaos-prod-developer
  namespace: kaos-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaos-prod-developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: gcp-osp-kaos@masmovil.com
  namespace: kaos-prod
