apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaos-prod-jenkins
  namespace: kaos-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaos-prod-jenkins
subjects:
- kind: ServiceAccount
  name: kaos-prod-jenkins
  namespace: kaos-prod