apiVersion: v1
kind: Secret
metadata:
  name: mongoman-secret
  namespace: mongo
type: Opaque
stringData:
  # URI format: mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
  # Password from mongo-secret (decoded): vqhdW8eMRHjW3I3RXZjNUA9B5EUpjARXfaXjGxGnAns=
  # URL Encoded Password: vqhdW8eMRHjW3I3RXZjNUA9B5EUpjARXfaXjGxGnAns%3D
  mongoman-uri: "mongodb://root:vqhdW8eMRHjW3I3RXZjNUA9B5EUpjARXfaXjGxGnAns%3D@mongo.mongo.svc.cluster.local:27017/admin?authSource=admin"
