apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama-embed

resources:
  - namespace.yaml
  - ollama-embed-pvc.yaml
  - ollama-embed-service.yaml
  - ollama-embed-deployment.yaml

