apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-embed-pvc
  namespace: ollama-embed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client

