apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner-system

resources:
  - ../../namespace.yaml
  - ../../rendered/10-controller.yaml
  - ../../rendered/20-runnerset.yaml
