networks:
  metabase:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 0.0.0.0/24

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - vol_persistente:/metabase-data/metabase.db
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: 
      MB_DB_DBNAME: 
      MB_DB_PORT: 5432
      MB_DB_USER: 
      MB_DB_PASS: 
      MB_DB_HOST: 
    networks:
      metabase:
        ipv4_address: 0.0.0.0
    healthcheck:
      test: curl --fail -I http://ipv4_address:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_PASSWORD: 
    networks:
      metabase:
        ipv4_address: 0.0.0.0
    volumes:
      - vol_persistente:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
