version: '3.8'

networks:
  metabase:
    driver: overlay
    attachable: true

volumes:
  metabase_data:
    driver: local
  postgres_data:
    driver: local

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: gv.bx8hi9PcBffmJeuaN
      MB_DB_HOST: postgres
    networks:
      - metabase
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: your_secure_password
    networks:
      - metabase
    deploy:
      placement:
        constraints:
          - node.role == manager