version: '3.8'

networks:
  metabase:
    driver: overlay
    attachable: true

volumes:
  metabase_data:
    driver: local
  postgres_data:
    driver: local

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: 
      MB_DB_PASS: 
      MB_DB_HOST: postgres
    networks:
      - metabase
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: 
    networks:
      - metabase
    deploy:
      placement:
        constraints:
          - node.role == manager