apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8-node-30
      tolerations:
      - key: "restricted"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: mysql
        image: mysql:8.0
        args:
          # Optimizaciones para entorno con poca RAM (4GB total en nodo, compartido con Zabbix)
          - "--default-authentication-plugin=mysql_native_password"
          - "--innodb-buffer-pool-size=256M" # Reducido para no saturar la RAM
          - "--max-connections=100"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:ubuntu-7.0-latest
        ports:
        - containerPort: 10050
          name: zabbix-agent
        env:
        - name: ZBX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZBX_SERVER_HOST
          value: "zabbix-server.zabbix.svc.cluster.local,172.16.64.148"
        - name: ZBX_METADATA
          value: "mysql"
        - name: ZBX_PLUGINS_MYSQL_SESSIONS_DEFAULT_URI
          value: "tcp://127.0.0.1:3306"
        - name: ZBX_PLUGINS_MYSQL_SESSIONS_DEFAULT_USER
          value: "root"
        - name: ZBX_PLUGINS_MYSQL_SESSIONS_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
