apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
stringData:
  # Cambiar en producción. Usuario root.
  mysql-root-password: "rootpassword"
  # Usuario para iTop y otros servicios
  mysql-user: "admin"
  mysql-password: "adminpassword"
