apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ../mongo/mongo-secret.yaml # Reutiliza el secreto existente de mongo
  - namespace.yaml
