networks:
  elk:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.fleet.registryUrl="https://epr.elastic.co"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.authc.realms.native.native1.order=0
    ports:
      - 9400:9300
      - 9500:9400
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      elk:
        ipv4_address: 172.20.0.2

  logstash:
    image: logstash-mongodb:latest
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    environment:
      - LOGSTASH_START=1
    depends_on:
      - elasticsearch
    networks:
      elk:
        ipv4_address: 172.20.0.4

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - xpack.fleet.agents.enabled=true
      - ELASTICSEARCH_USERNAME=user_kibana
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      - elasticsearch
    networks:
      elk:
        ipv4_address: 172.20.0.3

volumes:
  esdata:
    driver: local