apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-nfs-pvc
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
