apiVersion: v1
kind: Pod
metadata:
  name: zabbix-migration-pod
  namespace: zabbix
spec:
  nodeSelector:
    kubernetes.io/hostname: k8-manager
  containers:
  - name: migration
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Starting migration..."
        ls -la /old-data
        echo "Copying data..."
        cp -av /old-data/. /new-data/
        echo "Migration complete."
        ls -la /new-data
        sleep 3600
    volumeMounts:
    - name: old-data
      mountPath: /old-data
    - name: new-data
      mountPath: /new-data
  volumes:
  - name: old-data
    hostPath:
      path: /mnt/data/zabbix-server
      type: Directory
  - name: new-data
    persistentVolumeClaim:
      claimName: zabbix-server-nfs-pvc
  restartPolicy: Never
