site_name: 'Ka0s-Klaus Project Documentation'
site_description: 'Documentación del proyecto Ka0s-Klaus'
site_url: 'https://github.com/Ka0s-Klaus/ka0s'

nav:
  - Home: index.md
  - Documentation: core/docs/README.md
  - Core: core/docs/ka0s/ka0s.md

  # Añade aquí más secciones según tu estructura

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true

docs_dir: '.'