# Namespace para el stack ELK
# Este namespace contendrá todos los componentes: Elasticsearch, Logstash y Kibana
apiVersion: v1
kind: Namespace
metadata:
  name: elk
  labels:
    name: elk
    purpose: logging-and-analytics