# StatefulSet para Elasticsearch
# Despliega un clúster de Elasticsearch de 1 nodo con almacenamiento persistente
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      name: http
      targetPort: 9200
    - port: 9300
      name: transport
      targetPort: 9300
  selector:
    app: elasticsearch

---
# Headless Service para el StatefulSet de Elasticsearch
# Permite el descubrimiento de nodos dentro del clúster
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: elk
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  selector:
    app: elasticsearch

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-headless
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # Configuración de seguridad del pod
      securityContext:
        fsGroup: 1000

      # Inicialización: ajustar parámetros del sistema para Elasticsearch
      initContainers:
        - name: increase-vm-max-map-count
          image: busybox:1.36
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true

        - name: increase-fd-ulimit
          image: busybox:1.36
          command:
            - sh
            - -c
            - ulimit -n 65536
          securityContext:
            privileged: true

        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data

      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport

          # Variables de entorno para configurar Elasticsearch
          env:
            # Nombre del clúster
            - name: cluster.name
              value: "elk-cluster"

            # Nombre del nodo (basado en el nombre del pod)
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            # Modo de descubrimiento para un solo nodo
            - name: discovery.type
              value: "single-node"

            # Deshabilitar seguridad para facilitar pruebas iniciales
            - name: xpack.security.enabled
              value: "false"

            # Deshabilitar ML (Machine Learning) para reducir uso de recursos
            - name: xpack.ml.enabled
              value: "false"

            # Configuración de memoria JVM (50% de la memoria del contenedor)
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"

            # Deshabilitar bootstrap checks en desarrollo
            - name: bootstrap.memory_lock
              value: "false"

          # Recursos del contenedor
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          # Sonda de preparación: verifica que Elasticsearch está listo
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Sonda de vida: verifica que Elasticsearch está funcionando
          livenessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          # Montaje del volumen de datos
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data

  # Plantilla de PersistentVolumeClaim para cada réplica
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: elasticsearch
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi