# Use the official Logstash image as a base
FROM docker.elastic.co/logstash/logstash:8.5.0

# Install the logstash-input-mongodb plugin
RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-mongodb