apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic
  labels:
    app: kibana
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - port: 5601
      nodePort: 30002
      name: https
      targetPort: 5601