apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elastic
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 9600
      targetPort: 9600