version: '3.3'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
     - 8080:8080
    volumes:
     - /var/run:/var/run:ro
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro
     - /dev/disk/:/dev/disk:ro
    networks:
     - monitoring
    logging:
      driver: json-file
    deploy:
      mode: global
  grafana:
    image: grafana/grafana:latest
    user: nobody:nobody
    ports:
     - 3001:3000
    volumes:
     - grafana_data:/var/lib/grafana
    networks:
     - monitoring
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
  node-exporter:
    image: prom/node-exporter:latest
    command:
     - --path.procfs=/host/proc
     - --path.rootfs=/rootfs
     - --path.sysfs=/host/sys
     - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
     - 9100:9100
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /:/rootfs:ro
    networks:
     - monitoring
    logging:
      driver: json-file
    deploy:
      mode: global
  prometheus:
    image: prom/prometheus:latest
    command:
     - --config.file=/etc/prometheus/prometheus.yml
     - --storage.tsdb.path=/prometheus
    ports:
     - 9090:9090
    volumes:
     - prometheus_data:/prometheus
    networks:
     - monitoring
    configs:
     -
      source: prometheus_config
      target: /etc/prometheus/prometheus.yml
    logging:
      driver: json-file
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  monitoring:
    driver: overlay
volumes:
  grafana_data:
    external: true
  prometheus_data:
    external: true
configs:
  prometheus_config:
    external: true
