name: Ka0s C0re Host Audit logs
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write
env:
  KAOS_MODULE: "[Ka0S] CORE IaC"
  KAOS_PATH_RESUME: "audit/hosts/"
  KAOS_FILE_HOST: ${{ github.run_id }}
jobs:
  job-core:
    runs-on: 
      group: test
    steps:
      - id: repo
        name: Checkout repository
        if: ${{ success() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}

  job-audit:
    runs-on: 
      group: test
    needs: [job-core]
    steps:
      - id: audit
        name: Execute audit
        if: ${{ success() }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.KAOS_SSH_HOST_1 }}
          username: ${{ secrets.KAOS_SSH_USER }}
          key: ${{ secrets.KAOS_SSH_KEY_PRIV }}
          port: ${{ secrets.KAOS_SSH_PORT_1 }}
          script: |
            echo "${{ secrets.KAOS_SSH_PASS }}" | sudo -S lynis audit system --pentest --forensics 
        
  handle-success:
    runs-on: 
      group: test
    needs: [job-core, job-audit]
    if: ${{ success() }}
    steps: 
      - id: handle-success-execution
        run: |
          # Subimos el fichero de auditoria
          echo "${{ env.KAOS_MODULE }} Success in runid ${{ github.run_id }} initiated."
          # echo "Uploading files to Audit update repository ..."
          # git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
          # git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
          # git add ${{ env.KAOS_PATH_RESUME }}
          # if ! git diff --staged --quiet; then
          #    git commit -m "Ka0S] Uploading files to udit update repository ..."
          #    git push origin ${{ github.ref }}
          # fi
          
  handle_failure:
      runs-on: 
        group: test
      needs: [job-core, job-audit]
      if: ${{ failure() }} 
      steps: 
        - id: check-execution
          run: |
            # si ha existido un error dejamos la tarjeta In Review
            echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
            
  end-workflow:
    runs-on: 
      group: test
    needs: [job-core, job-audit, handle-success, handle_failure]
    if: ${{ always() }}
    steps:
      - id: end-process
        name: Finaliza el workflow
        run: |
          echo "End process"
          gh workflow run inspector.yaml --ref ${{ github.ref }} -f kaos-workflow-id="${{ env.KAOS_CODE }}"
