name: MongoDB Setup

on: [workflow_dispatch]

env:
  PYTHON_VERSION: '3.9'

jobs:
  mongo-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install pymongo

      - name: Configure MongoDB
        env:
          MONGO_SUPERUSER_CONNECTION: ${{ secrets.MONGO_SUPERUSER_CONNECTION }}
          MONGO_NEW_DB: ${{ github.event.inputs.db_name }}
          MONGO_NEW_USER: ${{ github.event.inputs.db_user }}
          MONGO_NEW_PASS: ${{ secrets.MONGO_USER_PASSWORD }}
        run: python mongo_admin_ci.py

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: mongo-setup-report
          path: ${{ env.REPORT_PATH }}