name: Ka0s DockerTest
on:
  workflow_dispatch:
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write
env:
  KAOS_MODULE: "[Ka0S] CORE IaC"
  GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
  KAOS_PATH_RESUME: "core/outputs/iac/r/"
  KAOS_RUNNER_JSON: "core/iac/r.json"
  KAOS_RUNNER_ACTION: "create"
  KAOS_RUNNER_GROUPNAME: "version"
  KAOS_PULL_IMAGE: "github-runner:25.04"
jobs:
  job-core:
    runs-on:
      group: ka0s
    steps:
        - id: repo
          name: bateria de pruebas de docker
          if: ${{ success() }}
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              token: ${{ secrets.KAOS_REPO_TOKEN }}
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.KAOS_HOST_1 }}
            username: ${{ secrets.KAOS_USER_CONNECT }}
            key: ${{ secrets.KAOS_SSHKEY_PRIVATE }}
            port: ${{ secrets.KAOS_PORT_1 }}
            script: |
              echo "Indicamos la posicion en el runner"
              pwd
              echo "Creando contenedor"
              docker ${{ env.KAOS_RUNNER_ACTION }} -i -t --name ${{ env.KAOS_RUNNER_GROUPNAME }}-2 ${{ secrets.KAOS_PULL_IMAGE }}
              echo "Iniciando el contenedor"
              docker start ${{ env.KAOS_RUNNER_GROUPNAME }}-2
              echo "Cargando la configuracion en el contenedor"
              docker exec -d ${{ env.KAOS_RUNNER_GROUPNAME }}-2 sh -c 'cd /actions-runner/ && ./config.sh --url https://github.com/Ka0s-Klaus --token ${{ secrets.KAOS_RUNNER_TOKEN }} --name ${{ env.KAOS_RUNNER_GROUPNAME }}-2 --runnergroup ${{ env.KAOS_RUNNER_GROUPNAME }} --labels ${{ env.KAOS_RUNNER_GROUPNAME }}-2 --work _work --unnattend && ./run.sh'
              echo "Ahora toca comprobar que el contenedor esta funcionando"
              
