name: Ka0s DockerTest
on:
  workflow_dispatch:
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write
env:
  KAOS_MODULE: "[Ka0S] CORE IaC"
  GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
  KAOS_PATH_RESUME: "core/outputs/iac/r/"
  KAOS_RUNNER_JSON: "core/iac/r.json"
  KAOS_RUNNER_ACTION: "create"
  KAOS_RUNNER_GROUPNAME: "core"
  KAOS_RUNNER_COUNT: 4
  KAOS_PULL_IMAGE: "github-runner:25.04"
jobs:
  job-core:
    runs-on:
      group: ka0s
    steps:
        - id: repo
          name: bateria de pruebas de docker
          if: ${{ success() }}
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              token: ${{ secrets.KAOS_REPO_TOKEN }}
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.KAOS_HOST_1 }}
            username: ${{ secrets.KAOS_USER_CONNECT }}
            key: ${{ secrets.KAOS_SSHKEY_PRIVATE }}
            port: ${{ secrets.KAOS_PORT_1 }}
            script: |
              echo "Comenzamos el proceso"
              for i in $(seq 1 ${{ env.KAOS_RUNNER_COUNT }}); do
                echo "Creando contenedor"
                container_name="${{ env.KAOS_RUNNER_GROUPNAME }}-$i!
                docker ${{ env.KAOS_RUNNER_ACTION }} -i -t --name $container_name ${{ secrets.KAOS_PULL_IMAGE }}
                echo "Iniciando el contenedor"
                docker start $container_name
                echo "Cargando la configuracion en el contenedor"
                docker exec ${{ env.KAOS_RUNNER_GROUPNAME }}-$i sh -c 'cd /actions-runner/ && ./config.sh --url https://github.com/Ka0s-Klaus --token ${{ secrets.KAOS_RUNNER_TOKEN }} --name $container_name --runnergroup ${{ env.KAOS_RUNNER_GROUPNAME }} --labels $container_name --work _work'
                echo "Ahora ejecutamos run en segundo plano y comprobamos los runner"
                docker exec -d $container_name sh -c 'cd /actions-runner/ && ./run.sh'
              done
              
