name: Ka0s ELK 
on: 
  workflow_dispatch: 
permissions:
  contents: read
jobs: 
  job-core: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0 
          token: ${{ secrets.KAOS_REPO_TOKEN }} 
        
      - name: Verify Core Paths 
        run: | 
          echo "Verificando rutas core..." 
          if [ ! -d "core/results" ]; then 
            echo "::error::La ruta core/results no existe" 
            exit 1
          else 
            RESULTS_SUBDIRS=$(find core/results -type d -maxdepth 1 -mindepth 1 | sed 's|core/results/||') 
            echo "Subcarpetas en core/results:" 
            echo "$RESULTS_SUBDIRS" 
          fi 
          if [ ! -d "core/outputs" ]; then 
            echo "::error::La ruta core/outputs no existe" 
            exit 1
          else 
            OUTPUTS_SUBDIRS=$(find core/outputs -type d -maxdepth 1 -mindepth 1 | sed 's|core/outputs/||') 
            echo "Subcarpetas en core/outputs:" 
            echo "$OUTPUTS_SUBDIRS" 
          fi