name: Ka0s JS Lint

on:
  workflow_dispatch:
    inputs:
      kaos-origin:
        description: 'Dispatcher Workflow Run ID'
        default: ""
        required: true
      kaos-files:
        description: 'Files Involved'
        default: ""
        required: true
      kaos-issue-id:
        description: 'Issue ID'
        default: "Kaos Issue ID"
        required: true
      kaos-user-start:
        description: 'User initiated process'
        default: ""
        required: true

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  KAOS_MODULE: "[Ka0S] JSLINT"
  GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
  KAOS_jslint_CONFIG: "core/config/"
  KAOS_PATH_RESUME: "core/outputs/js/"
  KAOS_REPO: "/actions-runner/_work/kaos/kaos"
  KAOS_STEP_MODULE: ""
  KAOS_CODE: ${{ github.run_id }}
  KAOS_REF_BRANCH: "main"

jobs:
  job-core:
    runs-on: 
      group: ka0s
    steps:
      - id: repo
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - id: install-node
        name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: install-jslint
        name: Install jslint
        run: |
            #if ! command -v jslint &> /dev/null; then
              echo "Installing jslint..."
              #npm install -g jslint-cli
            #else
              echo "jslint already installed, skipping installation"
            #fi
            #mkdir -p ${{ env.KAOS_PATH_RESUME }}
      - id: check-html
        name: Check HTML
        run: |
            file_name=$(basename "${{ github.event.inputs.kaos-files }}")
            touch ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt
            # jslint --rc ${{ env.KAOS_jslint_CONFIG }} ${{ github.event.inputs.kaos-files }} > ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt || true
            # cat ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt
            # if [ ! -s ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt ]; then
            #   echo "File ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt is empty and content is correct"
            #   KAOS_ISSUE_BODY="The ${{ env.KAOS_MODULE }} process (${{ github.event.inputs.kaos-origin }}) launched the check (${{ github.run_id }}) over file (${{ github.event.inputs.kaos-files }}) and its result has been SUCCESS. Please review all files implicated in pull request and approve to merge."
            #   gh issue comment ${{ github.event.inputs.kaos-issue-id }} -F ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt
            # else
            #   echo "File ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt is not empty and content is incorrect"
            #   KAOS_ISSUE_BODY="The ${{ env.KAOS_MODULE }} process (${{ github.event.inputs.kaos-origin }}) launched the check (${{ github.run_id }}) over file (${{ github.event.inputs.kaos-files }}) and its result has been FAILED. Please check and resolve the issues."
            #   gh issue comment ${{ github.event.inputs.kaos-issue-id }} -F ${{ env.KAOS_PATH_RESUME }}jslint-results-${{ github.run_id }}.txt
            # fi

  handle-success:
    runs-on:
      group: ka0s
    needs: [job-core]
    if: ${{ success() }}
    steps:
      - id: repo
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - id: handle-success-execution
        name: Handle Success Execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
        run: |
          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
          gh issue comment $RNNUMBER --body "El proceso ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado está en el fichero core/results/event_data_${{ env.KAOS_CODE }}.log"

  handle_failure:
    runs-on:
      group: ka0s
    needs: [job-core, handle-success]
    if: ${{ failure() }}
    steps:
      - id: repo
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - id: handle-failure-execution
        name: Handle Failure Execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
        run: |
          echo "Error detected in process"
          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
          gh issue comment $RNNUMBER --body "El proceso no ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado está en el fichero core/results/event_data_${{ env.KAOS_CODE }}.log"

  end-workflow:
    runs-on:
      group: ka0s
    needs: [job-core, handle-success, handle_failure]
    if: ${{ always() }}
    env:
        GH_TOKEN: ${{ secrets.KAOS_ACTIONS_TOKEN }}
    steps:
      - id: repo
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}
      - id: end-process
        name: Finaliza el workflow
        run: |
          echo "End process"
          RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
          gh issue comment $RNNUMBER --body "Se finaliza Ka0s ${{ env.KAOS_CODE }}"
          gh workflow run inspector.yml --ref 'main' -f kaos-issue-id=$RNNUMBER -f kaos-workflow-id="${{ env.KAOS_CODE }}" -f kaos-user-start=""
