name: Ka0s Initialize MongoDB Inspector Database

on:
  workflow_dispatch:

env:
    KAOS_PATH_MONGO: core/database/scripts/setup_mongo_inspector.sh
    MONGO_IMAGE: mongo:6.0

jobs:
  job-core:
    runs-on:
      group: ka0s
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.KAOS_REPO_TOKEN }}

    - name: Run MongoDB Tools via Docker
      run: |
        docker run --rm -v \$PWD:/workspace \
        -e HOST=${{ secrets.MONGO_HOST }} \
        -e ADMIN_USER=${{ secrets.MONGO_ADMIN_USER }} \
        -e ADMIN_PASS=${{ secrets.MONGO_ADMIN_PASS }} \
        -e DB_NAME=db_inspector \
        -e DB_USER=db_inspector \
        ${{ env.MONGO_IMAGE }} bash -c \
        "apt-get update -qq && \
        apt-get install -y -qq jq && \
        chmod +x /workspace/$KAOS_PATH_MONGO && \
        /workspace/$KAOS_PATH_MONGO ${{ secrets.DB_INITIAL_PASSWORD }}"

    - name: Commit script changes
      run: |
        git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
        git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
        git add .
        git commit -m '[Ka0s] Update MongoDB setup script' || echo 'No changes to commit'
        git push