name: Ka0s Scan Images
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nombre de la imagen Docker'
        required: true
        type: string
      dockerfile_path:
        description: 'Ruta al Dockerfile'
        required: true
        type: string
      version:
        description: 'Número de la versión (0.0.0)'
        required: true
        type: string

jobs:
  job-core:
    runs-on:
      group: swarm-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ka0score
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        if: success()
        run: |
          sudo docker build -t ${{ inputs.image_name }}:${{ inputs.version }}
    
      - name: Run Trivy vulnerability scanner
        id: scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ka0score/${{ inputs.image_name }}:${{ inputs.version }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Tag and Push if scan passes
        if: |
          success() &&
          contains(steps.scan.outputs.sarif, 'Total: 0 (HIGH: 0, CRITICAL: 0)')
        run: |
            # Añadimos la imagen a la version
            sudo docker tag ${{ inputs.image_name }}:${{ inputs.version }} ka0score/${{ inputs.image_name }}:${{ inputs.version }}
            echo "Se ha generado la version ka0score/${{ inputs.image_name }}:${{ inputs.version }} ...."
            # Añadimos la imagen a latest
            sudo docker tag ${{ inputs.image_name }}:${{ inputs.version }} ka0score/${{ inputs.image_name }}:latest
            echo "Se ha generado la version ka0score/${{ inputs.image_name }}:latest ...."
            # Subimos las imagenes
            sudo docker push ka0score/${{ inputs.image_name }}:${{ inputs.version }}
            echo 
            "Subida la imagen ka0score/${{ inputs.image_name }}:${{ inputs.version }} ...."
            sudo docker push ka0score/${{ inputs.image_name }}:latest
            "Subida la imagen ka0score/${{ inputs.image_name }}:latest ...."


      