name: Ka0s Scan Images
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nombre de la imagen Docker'
        required: true
        type: string
      dockerfile_path:
        description: 'Ruta al Dockerfile'
        required: true
        type: string
      version:
        description: 'Número de la versión (0.0.0)'
        required: true
        type: string

jobs:
  job-core:
    runs-on:
      group: swarm-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ka0score
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          tags: ka0score/${{ inputs.image_name }}:${{ inputs.version }}
          load: true
          push: false

      - name: Run Trivy vulnerability scanner
        id: scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ka0score/${{ inputs.image_name }}:${{ inputs.version }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Tag and Push if scan passes
        if: |
          success() &&
          contains(steps.scan.outputs.sarif, 'Total: 0 (HIGH: 0, CRITICAL: 0)')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ka0score/${{ inputs.image_name }}:${{ inputs.version }}