name: Create structure for dashboard
on:
  push:
    branches: [ main ]
    paths:
      - 'core/web/**'
  workflow_dispatch:
 
jobs:
  job-core:
    runs-on:
      group: ka0s
      steps:
      - id: upload-files
        name: Upload Files
        run: |
          echo "Uploading files to the repository..."
          git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
          git pull
          git add ${{ env.KAOS_JSON }}*
          git commit -m "[Ka0S] Uploading resume execution files to the repository..."
          git push origin ${{ github.ref }}
          git push origin $GITHUB_REF     